package mx.gob.sat.siat.ws.empleado.repository;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.gob.sat.siat.ws.empleado.serialization.arrays.ArrayOfint;
import mx.gob.sat.siat.ws.empleado.bean.ArrayOfEmpleado;
import mx.gob.sat.siat.ws.empleado.bean.ArrayOfFechasHabileseInhabiles;
import mx.gob.sat.siat.ws.empleado.bean.ArrayOfINPC;
import mx.gob.sat.siat.ws.empleado.bean.ArrayOfUnidadAdministrativa;
import mx.gob.sat.siat.ws.empleado.bean.ArrayOfVacacion;
import mx.gob.sat.siat.ws.empleado.bean.EmpleadoXml;
import mx.gob.sat.siat.ws.empleado.bean.EmpleadoCompletoXml;
import mx.gob.sat.siat.ws.empleado.bean.SalarioMinimoXml;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 *
 */
@WebService(name = "empleadoClientRepository", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    mx.gob.sat.siat.ws.empleado.serialization.arrays.ObjectFactory.class,
    mx.gob.sat.siat.ws.empleado.bean.ObjectFactory.class,
    mx.gob.sat.siat.ws.empleado.model.ObjectFactory.class,
    mx.gob.sat.siat.ws.empleado.serialization.ObjectFactory.class
})
public interface EmpleadoClientRepository {

    /**
     *
     * @param fechaFin
     * @param fechaInicio
     * @return returns
     * mx.gob.sat.siat.ws.empleado.bean.ArrayOfFechasHabileseInhabiles
     */
    @WebMethod(action = "http://tempuri.org/IServicioEmpleado/getCatalogoDiasHabilesInhabiles")
    @WebResult(name = "getCatalogoDiasHabilesInhabilesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCatalogoDiasHabilesInhabiles", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCatalogoDiasHabilesInhabiles")
    @ResponseWrapper(localName = "getCatalogoDiasHabilesInhabilesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCatalogoDiasHabilesInhabilesResponse")
    public ArrayOfFechasHabileseInhabiles getCatalogoDiasHabilesInhabiles(
            @WebParam(name = "FechaInicio", targetNamespace = "http://tempuri.org/") XMLGregorianCalendar fechaInicio,
            @WebParam(name = "FechaFin", targetNamespace = "http://tempuri.org/") XMLGregorianCalendar fechaFin);

    /**
     *
     * @param numeroEmpleado
     * @param idSistema
     * @param empleado
     * @return returns mx.gob.sat.siat.ws.empleado.bean.EmpleadoXml
     */
    @WebMethod(action = "http://tempuri.org/IServicioEmpleado/getEmpleado")
    @WebResult(name = "getEmpleadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getEmpleado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmpleado")
    @ResponseWrapper(localName = "getEmpleadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmpleadoResponse")
    public EmpleadoXml getEmpleado(
            @WebParam(name = "NumeroEmpleado", targetNamespace = "http://tempuri.org/") Integer numeroEmpleado,
            @WebParam(name = "Empleado", targetNamespace = "http://tempuri.org/") String empleado,
            @WebParam(name = "idSistema", targetNamespace = "http://tempuri.org/") Integer idSistema);

    /**
     *
     * @param numeroEmpleado
     * @param idmodulo
     * @param rfc
     * @return returns mx.gob.sat.siat.ws.empleado.bean.EmpleadoCompletoXml
     */
    @WebMethod(action = "http://tempuri.org/IServicioEmpleado/getEmpleadoCompleto")
    @WebResult(name = "getEmpleadoCompletoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getEmpleadoCompleto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmpleadoCompleto")
    @ResponseWrapper(localName = "getEmpleadoCompletoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmpleadoCompletoResponse")
    public EmpleadoCompletoXml getEmpleadoCompleto(
            @WebParam(name = "idmodulo", targetNamespace = "http://tempuri.org/") Integer idmodulo,
            @WebParam(name = "RFC", targetNamespace = "http://tempuri.org/") String rfc,
            @WebParam(name = "NumeroEmpleado", targetNamespace = "http://tempuri.org/") Integer numeroEmpleado);

    /**
     *
     * @param clavePerfil
     * @param claveALAF
     * @param idmodulo
     * @param claveModulo
     * @return returns mx.gob.sat.siat.ws.empleado.bean.ArrayOfEmpleado
     */
    @WebMethod(action = "http://tempuri.org/IServicioEmpleado/getEmpleadosXUnidadAdmva")
    @WebResult(name = "getEmpleadosXUnidadAdmvaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getEmpleadosXUnidadAdmva", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmpleadosXUnidadAdmva")
    @ResponseWrapper(localName = "getEmpleadosXUnidadAdmvaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetEmpleadosXUnidadAdmvaResponse")
    public ArrayOfEmpleado getEmpleadosXUnidadAdmva(
            @WebParam(name = "idmodulo", targetNamespace = "http://tempuri.org/") Integer idmodulo,
            @WebParam(name = "ClaveALAF", targetNamespace = "http://tempuri.org/") Integer claveALAF,
            @WebParam(name = "ClavePerfil", targetNamespace = "http://tempuri.org/") Integer clavePerfil,
            @WebParam(name = "ClaveModulo", targetNamespace = "http://tempuri.org/") Integer claveModulo);

    /**
     *
     * @param idmodulo
     * @return returns
     * mx.gob.sat.siat.ws.empleado.bean.ArrayOfUnidadAdministrativa
     */
    @WebMethod(action = "http://tempuri.org/IServicioEmpleado/getUnidadesAdministrativas")
    @WebResult(name = "getUnidadesAdministrativasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUnidadesAdministrativas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnidadesAdministrativas")
    @ResponseWrapper(localName = "getUnidadesAdministrativasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnidadesAdministrativasResponse")
    public ArrayOfUnidadAdministrativa getUnidadesAdministrativas(
            @WebParam(name = "idmodulo", targetNamespace = "http://tempuri.org/") Integer idmodulo);

    /**
     *
     * @param idmodulo
     * @param numeroEmpleados
     * @return returns mx.gob.sat.siat.ws.empleado.bean.ArrayOfEmpleado
     */
    @WebMethod(operationName = "InformacionEmpleados", action = "http://tempuri.org/IServicioEmpleado/InformacionEmpleados")
    @WebResult(name = "InformacionEmpleadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InformacionEmpleados", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InformacionEmpleados")
    @ResponseWrapper(localName = "InformacionEmpleadosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InformacionEmpleadosResponse")
    public ArrayOfEmpleado informacionEmpleados(
            @WebParam(name = "NumeroEmpleados", targetNamespace = "http://tempuri.org/") ArrayOfint numeroEmpleados,
            @WebParam(name = "idmodulo", targetNamespace = "http://tempuri.org/") Integer idmodulo);

    /**
     *
     * @param anio
     * @return returns mx.gob.sat.siat.ws.empleado.bean.ArrayOfINPC
     */
    @WebMethod(operationName = "TraeINPC", action = "http://tempuri.org/IServicioEmpleado/TraeINPC")
    @WebResult(name = "TraeINPCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TraeINPC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TraeINPC")
    @ResponseWrapper(localName = "TraeINPCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TraeINPCResponse")
    public ArrayOfINPC traeINPC(
            @WebParam(name = "anio", targetNamespace = "http://tempuri.org/") Integer anio);

    /**
     *
     * @return returns mx.gob.sat.siat.ws.empleado.bean.SalarioMinimoXml
     */
    @WebMethod(operationName = "TraeSalario", action = "http://tempuri.org/IServicioEmpleado/TraeSalario")
    @WebResult(name = "TraeSalarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TraeSalario", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TraeSalario")
    @ResponseWrapper(localName = "TraeSalarioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TraeSalarioResponse")
    public SalarioMinimoXml traeSalario();

    /**
     *
     * @param periodo
     * @return returns mx.gob.sat.siat.ws.empleado.bean.ArrayOfVacacion
     */
    @WebMethod(operationName = "TraeVacaciones", action = "http://tempuri.org/IServicioEmpleado/TraeVacaciones")
    @WebResult(name = "TraeVacacionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TraeVacaciones", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TraeVacaciones")
    @ResponseWrapper(localName = "TraeVacacionesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TraeVacacionesResponse")
    public ArrayOfVacacion traeVacaciones(
            @WebParam(name = "Periodo", targetNamespace = "http://tempuri.org/") Integer periodo);

    /**
     *
     * @param numeroEmpleado
     * @param idSistema
     * @param rfc
     * @return returns mx.gob.sat.siat.ws.empleado.bean.EmpleadoCompletoXml
     */
    @WebMethod(action = "http://tempuri.org/IServicioEmpleado/getInformacionEmpleado")
    @WebResult(name = "getInformacionEmpleadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getInformacionEmpleado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInformacionEmpleado")
    @ResponseWrapper(localName = "getInformacionEmpleadoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInformacionEmpleadoResponse")
    public EmpleadoCompletoXml getInformacionEmpleado(
            @WebParam(name = "idSistema", targetNamespace = "http://tempuri.org/") Integer idSistema,
            @WebParam(name = "RFC", targetNamespace = "http://tempuri.org/") String rfc,
            @WebParam(name = "NumeroEmpleado", targetNamespace = "http://tempuri.org/") Integer numeroEmpleado);

    /**
     *
     * @param idAdmGral
     * @return returns
     * mx.gob.sat.siat.ws.empleado.bean.ArrayOfUnidadAdministrativa
     */
    @WebMethod(action = "http://tempuri.org/IServicioEmpleado/getUnidadesAdministrativasPorGeneral")
    @WebResult(name = "getUnidadesAdministrativasPorGeneralResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUnidadesAdministrativasPorGeneral", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnidadesAdministrativasPorGeneral")
    @ResponseWrapper(localName = "getUnidadesAdministrativasPorGeneralResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnidadesAdministrativasPorGeneralResponse")
    public ArrayOfUnidadAdministrativa getUnidadesAdministrativasPorGeneral(
            @WebParam(name = "idAdmGral", targetNamespace = "http://tempuri.org/") Integer idAdmGral);

}
