package mx.gob.sat.siat.feagace.negocio.util.correo.campos;

public enum ReportType {
    INSUMO_TABLA_RESUMEN("aviso.asignacion.insumo.central.html"),
    ASIGNACION_INSUMO_ADMINISTRADOR("aviso.asignacion.insumo.administrador.html"),
    ASIGNACION_INSUMO_SUBADMINISTRADOR("aviso.asignacion.insumo.subadministrador.html"),
    AVISO_INSUMO_CAMBIO_SEMAFORO("aviso.insumo.cambio.semaforo.html"),
    AVISO_REASIGNACION_INSUMO_ADMINISTRADOR("aviso.reasignacion.insumo.administrador.html"),
    AVISO_ACEPTACION_REASIGNACION_INSUMO_ADMINISTRADOR("aviso.aceptacion.reasignacion.insumo.administrador.html"),
    AVISO_RECHAZO_REASIGNACION_INSUMO_ADMINISTRADOR("aviso.rechazo.reasignacion.insumo.administrador.html"),
    RETROALIMENTACION_INSUMO_ATENDIDA("retroalimentacion.insumo.atendida.html"),
    AVISO_RECHAZO_INSUMO("aviso.insumo.rechazado.html"),
    AVISO_SOLICITUD_RETROALIMENTACION_INSUMO("aviso.solicitud.retroalimentacion.insumo.html"),
    AVISO_CONTRIBUYENTE_PPEE_AMPARADO("aviso.contribuyente.ppee.amparado.html"),
    ASIGNACION_PROPUESTA("asignacion.propuesta.html"),
    ATENCION_RETROALIMENTACION_PROGRAMACION("atencion.retroalimentacion.programacion.html"),
    ATENCION_RECHAZO_RETROALIMENTACION_PROGRAMACION("atencion.rechazo.retroalimentacion.programacion.html"),
    TRANSFERENCIA_PROPUESTA_ASIGNACION_FIRMANTE("transferencia.propuesta.asignacion.firmante.html"),
    ASIGNACION_ORDEN_FIRMANTE("asignacion.orden.firmante.html"),
    ASIGNACION_ORDEN_AUDITOR("asignacion.orden.auditor.html"),
    SOLICITUD_VALIDACION_RECHAZO_PROPUESTA("solicitud.validacion.rechazo.propuesta.html"),
    SOLICITUD_VALIDACION_TRANSFERENCIA_PROPUESTA("solicitud.validacion.transferencia.propuesta.html"),
    SOLICITUD_RETROALIMENTACION_PROPUESTA("solicitud.retroalimentacion.propuesta.html"),
    SOLICITUD_RETROALIMENTACION_RECHAZO_PROPUESTA("solicitud.retroalimentacion.rechazo.propuesta.html"),
    SOLICITUD_VALIDACION_RECHAZO_PROPUESTA_SEGUIMIENTO("solicitud.validacion.rechazo.propuesta.seguimiento.html"),
    RECHAZO_PROPUESTA_ADECUAR("rechazo.propuesta.adecuar.html"),
    ORDEN_FIRMADA_SEGUIMIENTO("orden.firmada.seguimiento.html"),
    PROPUESTA_RECHAZADA_NO_FIRMADA("propuesta.rechazada.no.firmada.html"),
    AVISO_CARTAS_FIRMADAS_SEGUIMIENTO("aviso.cartas.firmadas.seguimiento.html"),
    AUTORIZACION_RECHAZO_PROPUESTA("autorizacion.rechazo.propuesta.html"),
    RECHAZO_VALIDACION_PROPUESTA_RECHAZADA("rechazo.validacion.propuesta.rechazada.html"),
    AUTORIZACION_ENVIO_PROPUESTA_TRANSFERIDA("autorizacion.envio.propuesta.transferida.html"),
    RECHAZO_SOLICITUD_TRANSFERENCIA_PROPUESTA("rechazo.solicitud.transferencia.propuesta.html"),
    AVISO_ASIGNACION_PROPUESTA_DE_FIRMANTE_A_ADMIN("aviso.asignacion.propuesta.firmante.asignacion.administrador.html"),
    AVISO_RECHAZO_PROPUESTA_POR_ADECUAR("aviso.rechazo.propuesta.adecuar.html"),
    AVISO_RECHAZO_VERIFICACION_PROCEDENCIA_DOCTO("aviso.rechazo.verificacion.procedencia.docto.html"),
    AVISO_ACEPTACION_RECHAZO_PENDIENTE_VALIDACION("aviso.rechazo.pendiente.validacion.html"),
    AVISO_RECHAZAR_RECHAZO_PENDIENTE_VALIDACION("aviso.rechazar.rechazo.pendiente.validacion.html"),
    AVISO_AUTORIZACION_ENVIO_PROPUESTA_TRANSFERIDA("aviso.autorizacion.envio.propuesta.transferida.html"),
    AVISO_RECHAZO_SOLICITUD_TRANSFERENCIA("aviso.rechazo.solicitud.transferencia.html"),
    AVISO_APROBACION_PROGRAMACION_CENTRAL_FIRMANTE("aviso.aprobacion.programacion.asignar.central.firmante.html"),
    AVISO_ATENCION_SOLICITUD_AREA_PROGRAMACION("aviso.atencion.solicitud.retroalimentacion.area.programacion.html"),
    AVISO_ATENCION_RECHAZO_SOLICITUD_PROGRAMACION("aviso.atencion.rechazo.solicitud.retroalimentacion.programacion.html"),
    AVISO_TRANSFERENCIA_PROPUESTA_ASIGNACION_FIRMANTE("aviso.transferencia.propuesta.asignacion.firmante.html"),
    AVISO_PROPUESTA_ASIGNADA_PARA_VALIDACION("aviso.propuesta.asignada.para.validacion.html"),
    AVISO_ASIGNACION_DOCUMENTO_VALIDACION_FIRMANTE("aviso.asignacion.documento.validacion.firmante.html"),
    AVISO_SOLICITUD_RETROALIMENTACION_PROPUESTA_RECHAZADA("aviso.solicitud.retroalimentacion.propuesta.rechazada.html"),
    AVISO_SOLICITUD_VALIDACION_PROPUESTA_RETROALIMENTADA("aviso.solicitud.validacion.propuesta.retroalimentada.html"),
    AVISO_SOLICITUD_VALIDACION_PROPUESTA_TRANSFERIDA("aviso.solicitud.validacion.propuesta.transferida.html"),
    AVISO_SOLICITUD_VALIDACION_RECHAZO_PROPUESTA("aviso.solicitud.validacion.rechazo.propuesta.html"),
    AVISO_SOLICITUD_VALIDACION_TRANSFERENCIA_PROPUESTA_RECHAZADA("aviso.validacion.transferencia.propuesta.rechazada.html"),
    AVISO_CARGA_DOCUMENTO_PROPUESTA("aviso.asignacion.documento.validacion.firmante.html"),
    AVISO_ASIGNACION_SUPLENCIA("aviso.asignacion.suplencia.html"),
    AVISO_ATENCION_REGISTRO_PROPUESTA_INDIVIDUAL("aviso.propuesta.asignada.para.validacion.html"),
    AVISO_PROPUESTA_RECHAZADA_VERIFICACION_DOCTO("aviso.propuesta.rechazada.verificacion.procedencia.documento.html"),
    AVISO_ORDEN_FIRMA_DOCTO("aviso.orden.firma.documento.electronico.html"),
    AVISO_RECHAZO_PROCEDENCIA_DOCTO_ELECTRONICO("aviso.aviso.rechazo.procedencia.docto.electronico.html"),
    AVISO_CARGA_DOCUMENTACION_PROMOCION_DOC_REQUERIDA("aviso.carga.documentacion.promocion.documentacion.requerida.html"),
    AVISO_CARGA_DOCUMENTACION_PROMOCION_PRUEBAS_ALEGATOS("aviso.carga.documentacion.promocion.pruebas.alegatos.html"),
    AVISO_SOLICITUD_PRORROGA("aviso.solicitud.prorroga.html"),
    AVISO_ASOCIADO_REGISTRADO("aviso.envio.asociado.registrado.html"),
    AVISO_ENVIO_OFICIO("aviso.envio.oficio.html"),
    AVISO_ENVIO_CAMBIO_METODO("aviso.envio.cambio.metodo.html"),
    AVISO_ENVIO_OFICIO_COMPULSA_TERCEROS("aviso.envio.oficio.compulsa.terceros.html"),
    AVISO_ENVIO_RESOLUCION_PRORROGA("aviso.envio.resolucion.prorroga.html"),
    AVISO_ENVIO_SEGUIMIENTO_OFICIOS_AUDITOR("aviso.envio.seguimiento.oficios.auditor.html"),
    AVISO_ENVIO_RECHAZO_OFICIOS_AUDITOR("aviso.envio.rechazo.oficios.auditor.html"),
    AVISO_ENVIO_OFICIO_FIRMANTE("aviso.oficio.pendiente.firmante.html"),
    AVISO_ENVIO_OFICIO_FIRMANTE_METODO("aviso.oficio.pendiente.firmante.metodo.html"),
    AVISO_ENVIO_OFICIO_FIRMANTE_COMPULSA("aviso.oficio.pendiente.firmante.compulsa.html"),
    AVISO_ENVIO_PRORROGA_FIRMANTE("aviso.prorroga.pendiente.firmante.html"),
    AVISOS_INSUMO_GENERICO("avisos.insumo.html"),
    AVISOS_INSUMO_MASIVO("avisos.insumo.masivo.html"),
    AVISOS_INSUMO_GENERICO_RFC("avisos.insumo.rfc.html"),
    AVISOS_PROPUESTA_GENERICO("avisos.propuesta.html"),
    AVISO_ENVIO_PRUEBA_PERICIAL_FIRMANTE("aviso.prorroga.pendiente.firmante.html"),
    AVISOS_ORDEN_GENERICO("avisos.ordenes.html"),
    AVISO_AVISOS_CONCLUSIVOS("avisos.acuerdos.conclusivos.html"),
    AVISO_SOLICITUD_PRUEBAS_PERICIALES("aviso.solicitud.prueba.pericial.html");
    
    
    private String name;
    
    private ReportType(String name) {
        this.name = name;
    }
    
    public String getName() {
        return this.name;
    }
}