package mx.gob.sat.siat.feagace.modelo.dao.insumos.sql;

/**
 *
 * @author Ing. Emmanuel Estrada Gonzalez
 */
public interface FecetRetroalimentacionSQL {

    String DETALLE_RETRO_X_ID_PROPUESTA = "SELECT FECET_RETROALIMENTACION.ID_RETROALIMENTACION, \n"
            + "FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION AS FECHA_CREACION, \n FECEC_MOTIVO.ID_MOTIVO, \n"
            + "FECEC_MOTIVO.DESCRIPCION, \n FECEC_MOTIVO.TIPO_MOTIVO, \n"
            + "COUNT(FECET_DOC_RETRO_PROPUESTA.RUTA_ARCHIVO) TOTAL \n FROM FECET_DOC_RETRO_PROPUESTA \n"
            + "INNER JOIN FECET_RETROALIMENTACION ON FECET_RETROALIMENTACION.ID_RETROALIMENTACION = FECET_DOC_RETRO_PROPUESTA.ID_RETROALIMENTACION  \n"
            + "INNER JOIN FECEC_MOTIVO ON FECEC_MOTIVO.ID_MOTIVO = FECET_RETROALIMENTACION.ID_MOTIVO \n"
            + "WHERE FECET_DOC_RETRO_PROPUESTA.ID_PROPUESTA = ? and FECET_RETROALIMENTACION.BLN_ESTATUS=1 \n"
            + "GROUP BY FECET_RETROALIMENTACION.ID_RETROALIMENTACION, \n"
            + "FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION, \n FECEC_MOTIVO.ID_MOTIVO, \n"
            + "FECEC_MOTIVO.DESCRIPCION, \n FECEC_MOTIVO.TIPO_MOTIVO  \n"
            + "ORDER BY FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION DESC";

    String DETALLE_RETRO_X_ID_ORIGEN = "SELECT \n"
            + "FECET_RETROALIMENTACION.ID_RETROALIMENTACION,\n"
            + "FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION AS FECHA_CREACION, \n"
            + "FECEC_MOTIVO.ID_MOTIVO,\n"
            + "FECEC_MOTIVO.DESCRIPCION, \n"
            + "FECEC_MOTIVO.TIPO_MOTIVO,\n"
            + "COUNT(FECET_DOC_RETRO_PROPUESTA.RUTA_ARCHIVO) TOTAL FROM FECET_DOC_RETRO_PROPUESTA \n"
            + "INNER JOIN FECET_RETROALIMENTACION ON FECET_RETROALIMENTACION.ID_RETROALIMENTACION = FECET_DOC_RETRO_PROPUESTA.ID_RETROALIMENTACION \n"
            + "INNER JOIN FECEC_MOTIVO ON FECEC_MOTIVO.ID_MOTIVO  = FECET_RETROALIMENTACION.ID_MOTIVO \n"
            + "INNER JOIN FECEC_MOTIVO ON FECEC_MOTIVO.ID_MOTIVO  = FECET_RETROALIMENTACION.ID_MOTIVO \n"
            + "WHERE FECET_RETROALIMENTACION.ID_RETROALIMENTACION = ? \n"
            + "GROUP BY \n"
            + "FECET_RETROALIMENTACION.ID_RETROALIMENTACION, \n"
            + "FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION, \n"
            + "FECEC_MOTIVO.ID_MOTIVO, \n"
            + "FECEC_MOTIVO.DESCRIPCION, \n"
            + "FECEC_MOTIVO.TIPO_MOTIVO  \n"
            + "ORDER BY FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION DESC";

    String DETALLE_RETRO_HISTORIAL_ID_PROPUESTA = new StringBuilder()
            .append("SELECT FECET_RETROALIMENTACION.ID_RETROALIMENTACION,\n ")
            .append("FECEA_PROPUESTA_RETRO.ID_RETROALIMENTACION_ORIGEN,\n ")
            .append("FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION AS FECHA_CREACION, \n FECEC_MOTIVO.ID_MOTIVO, \n ")
            .append("FECEC_MOTIVO.DESCRIPCION, \n  FECEC_MOTIVO.TIPO_MOTIVO, \n ")
            .append("FECET_RETROALIMENTACION.ID_PROPUESTA,\n FECET_RETROALIMENTACION.ID_UNIDAD_ADMINISTRATIVA,\n ")
            .append("FECET_RETROALIMENTACION.ID_SUBPROGRAMA,\n  FECET_RETROALIMENTACION.ID_METODO,\n ")
            .append("FECET_RETROALIMENTACION.ID_REVISION,\n  FECET_RETROALIMENTACION.ID_TIPO_PROPUESTA,\n ")
            .append("FECET_RETROALIMENTACION.ID_CAUSA_PROGRAMACION,\n  FECET_RETROALIMENTACION.ID_SECTOR,\n ")
            .append("FECET_RETROALIMENTACION.FECHA_INICIO_PERIODO,\n  FECET_RETROALIMENTACION.FECHA_FIN_PERIODO, \n ")
            .append("FECET_RETROALIMENTACION.FECHA_PRESENTACION, \n  FECET_RETROALIMENTACION.FECHA_INFORME, \n ")
            .append("FECET_RETROALIMENTACION.PRIORIDAD,  \n  FECET_RETROALIMENTACION.FECHA_CREACION,FECET_RETROALIMENTACION.DESCRIPCION AS DESCRIPCION_RETRO ,\n ")
            .append("FECEC_SUBPROGRAMA.ID_SUBPROGRAMA AS SUBPROGRAMA_ID,   \n ")
            .append("FECEC_SUBPROGRAMA.CLAVE AS SUBPROGRAMA_CLAVE, \n ")
            .append("FECEC_SUBPROGRAMA.DESCRIPCION AS DESCRIPCION_SUBPROGRAMA,  \n ")
            .append("FECEC_METODO.ID_METODO AS METODO_ID,  \n  FECEC_METODO.ABREVIATURA AS METODO_ABREVIATURA,   \n ")
            .append("FECEC_METODO.NOMBRE AS NOMBRE_METODO, \n ")
            .append("FECEC_SECTOR.DESCRIPCION AS DESCRIPCION_SECTOR, \n  FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA,\n ")
            .append("FECEC_TIPO_PROPUESTA.DESCRIPCION AS DESCRIPCION_TIPO_PROPUESTA, \n ")
            .append("FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION, \n ")
            .append("FECEC_CAUSA_PROGRAMACION.DESCRIPCION AS DESCRIPCION_CAUSA_PROGRAMACION, \n ")
            .append("FECEC_REVISION.ID_REVISION,    \n ")
            .append("FECEC_REVISION.DESCRIPCION AS DESCRIPCION_REVISION,\n ")
            .append("COUNT(FECET_DOC_RETRO_PROPUESTA.RUTA_ARCHIVO) TOTAL  \n   FROM FECET_DOC_RETRO_PROPUESTA \n ")
            .append("INNER JOIN FECET_RETROALIMENTACION ON FECET_RETROALIMENTACION.ID_RETROALIMENTACION = FECET_DOC_RETRO_PROPUESTA.ID_RETROALIMENTACION  \n ")
            .append("LEFT JOIN FECEC_MOTIVO ON FECEC_MOTIVO.ID_MOTIVO = FECET_RETROALIMENTACION.ID_MOTIVO \n ")
            .append("LEFT JOIN FECEC_SUBPROGRAMA ON FECEC_SUBPROGRAMA.ID_SUBPROGRAMA = FECET_RETROALIMENTACION.ID_SUBPROGRAMA \n ")
            .append("LEFT JOIN FECEC_METODO ON FECEC_METODO.ID_METODO = FECET_RETROALIMENTACION.ID_METODO \n ")
            .append("LEFT JOIN  FECEC_REVISION ON FECEC_REVISION.ID_REVISION = FECET_RETROALIMENTACION.ID_REVISION \n ")
            .append("LEFT JOIN FECEC_TIPO_PROPUESTA ON FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA = FECET_RETROALIMENTACION.ID_TIPO_PROPUESTA \n ")
            .append("LEFT JOIN FECEC_CAUSA_PROGRAMACION ON FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION = FECET_RETROALIMENTACION.ID_CAUSA_PROGRAMACION \n ")
            .append("LEFT JOIN FECEC_SECTOR ON FECEC_SECTOR.ID_SECTOR = FECET_RETROALIMENTACION.ID_SECTOR \n ")
            .append("INNER JOIN FECEA_PROPUESTA_RETRO ON FECEA_PROPUESTA_RETRO.ID_RETROALIMENTACION = FECET_RETROALIMENTACION.ID_RETROALIMENTACION \n ")
            .append("WHERE FECET_DOC_RETRO_PROPUESTA.ID_PROPUESTA = ? and FECEA_PROPUESTA_RETRO.ID_RETROALIMENTACION_ORIGEN!=0 \n ")
            .append("GROUP BY FECET_RETROALIMENTACION.ID_RETROALIMENTACION, \n ")
            .append("FECEA_PROPUESTA_RETRO.ID_RETROALIMENTACION_ORIGEN, \n ")
            .append("FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION, FECEC_MOTIVO.ID_MOTIVO, \n ")
            .append("FECEC_MOTIVO.DESCRIPCION, FECEC_MOTIVO.TIPO_MOTIVO, \n ")
            .append("FECET_RETROALIMENTACION.ID_PROPUESTA,FECET_RETROALIMENTACION.ID_UNIDAD_ADMINISTRATIVA,\n ")
            .append("FECET_RETROALIMENTACION.ID_SUBPROGRAMA,FECET_RETROALIMENTACION.ID_METODO,\n ")
            .append("FECET_RETROALIMENTACION.ID_REVISION,FECET_RETROALIMENTACION.ID_TIPO_PROPUESTA,\n ")
            .append("FECET_RETROALIMENTACION.ID_CAUSA_PROGRAMACION,FECET_RETROALIMENTACION.ID_SECTOR,\n ")
            .append("FECET_RETROALIMENTACION.FECHA_INICIO_PERIODO,FECET_RETROALIMENTACION.FECHA_FIN_PERIODO, \n ")
            .append("FECET_RETROALIMENTACION.FECHA_PRESENTACION, FECET_RETROALIMENTACION.FECHA_INFORME, \n ")
            .append("FECET_RETROALIMENTACION.PRIORIDAD, FECET_RETROALIMENTACION.FECHA_CREACION, \n ")
            .append("FECEC_SUBPROGRAMA.ID_SUBPROGRAMA ,  FECEC_SUBPROGRAMA.CLAVE , \n ")
            .append("FECEC_SUBPROGRAMA.DESCRIPCION , FECEC_METODO.ID_METODO,  \n ")
            .append("FECEC_METODO.ABREVIATURA, FECEC_METODO.NOMBRE, \n ")
            .append("FECEC_SECTOR.DESCRIPCION,   FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA,  \n ")
            .append("FECEC_TIPO_PROPUESTA.DESCRIPCION, FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION, \n ")
            .append("FECEC_CAUSA_PROGRAMACION.DESCRIPCION, FECEC_REVISION.ID_REVISION,    \n ")
            .append("FECEC_REVISION.DESCRIPCION,FECET_RETROALIMENTACION.DESCRIPCION ")
            .append("ORDER BY FECET_RETROALIMENTACION.FECHA_RETROALIMENTACION DESC").toString();

    String DETALLE_DOC_RETRO_X_ID_RETRO = "SELECT \n FECET_DOC_RETRO_PROPUESTA.ID_RETROALIMENTACION, \n"
            + "FECET_DOC_RETRO_PROPUESTA.ID_PROPUESTA, \n FECET_DOC_RETRO_PROPUESTA.RUTA_ARCHIVO, \n"
            + "FECET_DOC_RETRO_PROPUESTA.FECHA_CREACION FROM FECET_DOC_RETRO_PROPUESTA \n"
            + "WHERE ID_RETROALIMENTACION = ?";

    String INSER_RETROALIMENTACION = "INSERT INTO \n FECET_RETROALIMENTACION ( \n FECHA_CREACION,\n"
            + "ID_RETROALIMENTACION, \n ID_PROPUESTA, \n ID_MOTIVO, \n DESCRIPCION, \n"
            + "RFC_RETROALIMENTACION, \n FECHA_RETROALIMENTACION, \n FECHA_RECHAZO, \n"
            + "DESCRIPCION_RECHAZO, \n ID_EMPLEADO, \n ID_ESTATUS, \n BLN_ESTATUS) \n"
            + "VALUES ( SYSDATE,FECEQ_RETROALIMENTACION.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    String ACTUALIZAR_ESTADOS_RETROALIMENTACION = "UPDATE FECET_RETROALIMENTACION \n SET BLN_ESTATUS = ?\n"
            + "WHERE ID_PROPUESTA = ?";

    String OBTENER_ID_RETROALIMENTACION_X_ESTADO = "SELECT \n ID_RETROALIMENTACION FROM \n"
            + "FECET_RETROALIMENTACION\n WHERE \n ID_PROPUESTA = ?\n AND\n BLN_ESTATUS = ?";

    String UPDATE_ESTADO_RETROALIMENTACION = "UPDATE FECET_RETROALIMENTACION \n SET BLN_ESTATUS = ? \n"
            + "WHERE ID_RETROALIMENTACION = ? ";
}
