package mx.gob.sat.siat.ws.nyv.client.repository;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.gob.sat.siat.ws.nyv.v2.bean.ObjectFactory;
import mx.gob.sat.siat.ws.nyv.v2.bean.RegistroActoAdministrativoVO;
import mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsulta;
import mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsultaActosAdmin;
import mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsultaNumeroReferencia;
import mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsultaTiposProceso;
import mx.gob.sat.siat.ws.nyv.v2.bean.ResponseRegistro;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 *
 */
@WebService(name = "wsNyVV2Repository", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSNyVV2Repository {

    /**
     *
     * @param registroActoAdministrativo
     * @return returns mx.gob.sat.siat.ws.nyv.v2.bean.ResponseRegistro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarActoAdministrativo", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.RegistrarActoAdministrativo")
    @ResponseWrapper(localName = "registrarActoAdministrativoResponse", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.RegistrarActoAdministrativoResponse")
    public ResponseRegistro registrarActoAdministrativo(
            @WebParam(name = "registroActoAdministrativo", targetNamespace = "") RegistroActoAdministrativoVO registroActoAdministrativo);

    /**
     *
     * @param folioActoAdministrativo
     * @return returns mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarActoAdministrativo", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarActoAdministrativo")
    @ResponseWrapper(localName = "consultarActoAdministrativoResponse", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarActoAdministrativoResponse")
    public ResponseConsulta consultarActoAdministrativo(
            @WebParam(name = "folioActoAdministrativo", targetNamespace = "") String folioActoAdministrativo);

    /**
     *
     * @param unidadAdministrativa
     * @return returns mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsultaActosAdmin
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaActosAdmin", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarListaActosAdmin")
    @ResponseWrapper(localName = "consultarListaActosAdminResponse", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarListaActosAdminResponse")
    public ResponseConsultaActosAdmin consultarListaActosAdmin(
            @WebParam(name = "unidadAdministrativa", targetNamespace = "") String unidadAdministrativa);

    /**
     *
     * @param unidadAdministrativa
     * @return returns
     * mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsultaTiposProceso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarListaTiposProceso", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarListaTiposProceso")
    @ResponseWrapper(localName = "consultarListaTiposProcesoResponse", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarListaTiposProcesoResponse")
    public ResponseConsultaTiposProceso consultarListaTiposProceso(
            @WebParam(name = "unidadAdministrativa", targetNamespace = "") String unidadAdministrativa);

    /**
     *
     * @param numeroReferencia
     * @return returns
     * mx.gob.sat.siat.ws.nyv.v2.bean.ResponseConsultaNumeroReferencia
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarNumeroReferencia", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarNumeroReferencia")
    @ResponseWrapper(localName = "consultarNumeroReferenciaResponse", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.ConsultarNumeroReferenciaResponse")
    public ResponseConsultaNumeroReferencia consultarNumeroReferencia(
            @WebParam(name = "numeroReferencia", targetNamespace = "") String numeroReferencia);

    /**
     *
     * @return returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fueraHorarioLaboral", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.FueraHorarioLaboral")
    @ResponseWrapper(localName = "fueraHorarioLaboralResponse", targetNamespace = "http://webservice.sistema.nyv.siat.sat.gob.mx/", className = "mx.gob.sat.siat.ws.nyv.v2.bean.FueraHorarioLaboralResponse")
    public boolean fueraHorarioLaboral();

}
