package mx.gob.sat.siat.feagace.modelo.enums.nyv;

public enum TipoActoAdministrativoEnum {
    
    UNICA_CARTA_INVITACION(1L,6336L,"UNICA CARTA INVITACION"),
    SEGUNDA_UNICA_CARTA_INVITACION(2L,6372L,"SEGUNDA UNICA CARTA INVITACION"),
    UNICA_CARTA_INVITACION_MASIVA(3L,6336L,"UNICA CARTA INVITACION MASIVA"),
    SEGUNDA_UNICA_CARTA_INVITACION_MASIVA(4L,6378,"SEGUNDA UNICA CARTA INVITACION MASIVA"),
    CAMBIO_DE_METODO(5L,6336L,"CAMBIO DE METODO"),
    CONCLUSION(6L,6373L,"CONCLUSION"),
    CANCELACION_DE_ORDEN(7L,6359L,"CANCELACION DE ORDEN"),
    ORDEN_DE_REVISION_DE_GABINETE(8L,6355,"ORDEN DE REVISION DE GABINETE"),
    CONCLUSION_DE_REVISION_DE_ESCRITORIO_POR_IMPOSIBILIDAD_MATERIAL_PARA_SU_DESAHOGO(9L,6358L,"CONCLUSION DE REVISION DE ESCRITORIO POR IMPOSIBILIDAD MATERIAL PARA SU DESAHOGO"),
    SUSPENSION_EN_PADRON_DE_IMPORTADORES_Y_EXPORTADORES(10L,6369L,"SUSPENSION EN PADRON DE IMPORTADORES Y EXPORTADORES"),
    CONCLUSION_SIN_OBSERVACIONES(11L,6361L,"CONCLUSION SIN OBSERVACIONES"),
    OBSERVACIONES_EN_REVISION_DE_ESCRITORIO(12L,6360L,"OBSERVACIONES EN REVISION DE ESCRITORIO"),
    IMPOSICION_DE_MULTA(13L,6367L,"IMPOSICION DE MULTA"),
    IMPOSICION_DE_MULTA_POR_REINCIDENCIA(14L,6367L,"IMPOSICION DE MULTA POR REINCIDENCIA"),
    REQUERIMIENTO_POR_REINCIDENCIA(15L,6366L,"REQUERIMIENTO POR REINCIDENCIA"),
    OFICIO_DE_MULTA(16L,6368L,"OFICIO DE MULTA"),
    OTRAS_AUTORIDADES(17L,6370L,"OTRAS AUTORIDADES"),
    SEGUNDO_REQUERIMIENTO(18L,6357L,"SEGUNDO REQUERIMIENTO"),
    COMPULSA_INTERNACIONAL(19L,6364L,"COMPULSA INTERNACIONAL"),
    COMPULSA_CON_TERCEROS(20L,6363,"COMPULSA CON TERCEROS"),
    AVISO_A_CONTRIBUYENTE(21L,6382L,"AVISO A CONTRIBUYENTE"),
    RESOLUCION_DEFINITIVA(22L,6362L,"RESOLUCION DEFINITIVA"),
    ESCRITORIO_DE_ECHOS_U_OMICIONES(23L,6356L,"ESCRITORIO DE ECHOS U OMICIONES"),
    PRUEBAS_DE_DESAHOGO(24L,6371L,"PRUEBAS DE DESAHOGO"),
    PRUEBAS_PERICIALES_PARA_EL_DESAHOGO(25L,6374L,"PRUEBAS PERICIALES PARA EL DESAHOGO"),
    RESOLUCION_PROVISIONAL(26L,6337,"RESOLUCION PROVISIONAL");
    
    private final long idTipoActoAdministrativo;
    private final long claveTipoActoAdministrativo;
    private final String descricpcion;
    
    TipoActoAdministrativoEnum(long idTipoActoAdministrativo,long claveTipoActoAdministrativo,String descricpcion){
        this.idTipoActoAdministrativo= idTipoActoAdministrativo;
        this.claveTipoActoAdministrativo = claveTipoActoAdministrativo;
        this.descricpcion = descricpcion;
    }


    public long getIdTipoActoAdministrativo() {
        return idTipoActoAdministrativo;
    }

    public long getClaveTipoActoAdministrativo() {
        return claveTipoActoAdministrativo;
    }

    public String getDescricpcion() {
        return descricpcion;
    }
}
