/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.siat.feagace.modelo.dao.propuestas.sql;

/**
 *
 * @author Ing. Emmanuel Estrada Gonzalez
 */
public interface DocTransferenciaSQL {

    String INSERT_DOC_TRANSFERENCIA = "INSERT INTO \n"
            + "FECET_DOC_TRANSFERENCIA ( ID_DOC_TRANSFERENCIA, ID_PROPUESTA, ID_TRANSFERENCIA, RUTA_ARCHIVO, FECHA_CREACION,BLN_ACTIVO)\n"
            + "VALUES ( FECEQ_DOCTRANSFERENCIA.NEXTVAL,?,?,?,SYSDATE,?)";

    String ARCHIVOS_TRANSFERENCIA_X_IDPROPUESTA_IDTRANSFERENCIA = "SELECT  ID_PROPUESTA,\n"
            + "ID_TRANSFERENCIA,\n"
            + "ID_DOC_TRANSFERENCIA,\n"
            + "RUTA_ARCHIVO,\n"
            + "FECHA_CREACION\n"
            + "FROM FECET_DOC_TRANSFERENCIA \n"
            + "WHERE \n"
            + "ID_PROPUESTA = ?\n"
            + "AND ID_TRANSFERENCIA = ?\n"
            + "ORDER BY ID_TRANSFERENCIA";

    String ARCHIVOS_TRANSFERENCIA_X_ID_TRANSFERENCIA_ESTATUS = "SELECT  ID_PROPUESTA, ID_TRANSFERENCIA, ID_DOC_TRANSFERENCIA, RUTA_ARCHIVO, FECHA_CREACION "
            + "\n FROM FECET_DOC_TRANSFERENCIA "
            + "\n WHERE ID_TRANSFERENCIA = ? "
            + "\n AND BLN_ACTIVO = ?\n"
            + "ORDER BY ID_TRANSFERENCIA";

    String ARCHIVOS_TRANSFERENCIA_X_ID_TRANSFERENCIA = "SELECT  ID_PROPUESTA, ID_TRANSFERENCIA, ID_DOC_TRANSFERENCIA, RUTA_ARCHIVO, FECHA_CREACION "
            + "\n FROM FECET_DOC_TRANSFERENCIA "
            + "\n WHERE ID_TRANSFERENCIA = ? "
            + "\n ORDER BY ID_TRANSFERENCIA";

    String OBTENER_TRANSFERENCIA_X_IDPROPUESTA_BLNESTATUS = "SELECT FECET_TRANSFERENCIA.ID_TRANSFERENCIA,\n"
            + "FECET_TRANSFERENCIA.ID_PROPUESTA,\n"
            + "FECET_TRANSFERENCIA.ID_ARACE_ORIGEN,\n"
            + "FECET_TRANSFERENCIA.ID_ARACE_DESTINO,\n"
            + "FECET_TRANSFERENCIA.ID_EMPLEADO,\n"
            + "FECET_TRANSFERENCIA.ID_ESTATUS,\n"
            + "FECET_TRANSFERENCIA.ID_TRANSFERENCIA_NUEVA,\n"
            + "FECET_TRANSFERENCIA.BLN_ESTATUS TRANSFERENCIA_BLN_ESTATUS,\n"
            + "FECET_TRANSFERENCIA.OBSERVACIONES,\n"
            + "FECET_DOC_TRANSFERENCIA.BLN_ACTIVO DOC_TRANSFER_BLN_ACTIVO,\n"
            + "FECET_DOC_TRANSFERENCIA.ID_DOC_TRANSFERENCIA,\n"
            + "FECET_DOC_TRANSFERENCIA.RUTA_ARCHIVO\n"
            + "FROM FECET_TRANSFERENCIA\n"
            + "INNER JOIN FECET_DOC_TRANSFERENCIA ON FECET_TRANSFERENCIA.ID_PROPUESTA = FECET_DOC_TRANSFERENCIA.ID_PROPUESTA\n"
            + "WHERE FECET_TRANSFERENCIA.ID_TRANSFERENCIA_NUEVA = ? \n"
            + "AND FECET_DOC_TRANSFERENCIA.BLN_ACTIVO = ?";
}
