/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.siat.feagace.modelo.dao.propuestas.sql;

/**
 *
 * @author Ing. Emmanuel Estrada Gonzalez
 */
public interface PropuestasSQL {

    String NAME_TABLE = "FECET_PROPUESTA";

    String FROM_TABLE = "FROM " + NAME_TABLE + " \n";

    String NAME_ID_TABLE = "ID_PROPUESTA";

    String SALTO_LINEA = "\n";

    String COUNT_ACCIONES_PROPUESTAS = " (SELECT COUNT(0) FROM FECET_PROPUESTA P INNER JOIN FECEA_PROPUESTA_ACCION PA ON P.ID_PROPUESTA = PA.ID_PROPUESTA ";

    String COLUMNAS_PRIMARIAS = "ID_PROPUESTA,\n" + "ID_CONTRIBUYENTE,\n" + "ID_ARACE,\n" + "ID_SUBPROGRAMA,\n"
            + "ID_METODO,\n" + "ID_REVISION,\n" + "ID_TIPO_PROPUESTA,\n" + "ID_CAUSA_PROGRAMACION,\n" + "ID_SECTOR,\n"
            + "ID_REGISTRO,";

    String INSERTAR = "INSERT INTO " + NAME_TABLE + "(" + COLUMNAS_PRIMARIAS + "ID_ESTATUS,\n" + "ID_INSUMO,\n"
            + "ID_REGISTRO_INSUMO,\n" + "ID_ORIGEN,\n" + "ID_PROGRAMADOR,\n" + "FECHA_INICIO_PERIODO,\n"
            + "FECHA_FIN_PERIODO,\n" + "FECHA_PRESENTACION,\n" + "FECHA_INFORME,\n" + "FECHA_BAJA,\n"
            + "CONSECUTIVO_ANO,\n" + "PRIORIDAD,\n" + "RFC_CREACION,\n" + "RFC_ADMINISTRADOR,\n"
            + "RFC_SUBADMINISTRADOR,\n" + "RFC_AUDITOR,\n" + "RFC_FIRMANTE,\n" + "INFORME_PRESENTACION,\n"
            + "FECHA_CREACION" + ") \n" + "VALUES(FECEQ_PROPUESTA.NEXTVAL,\n" + "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
            + "?,?,?,?,?,\n" + "?,?,?,?,?,?,?," + "SYSDATE)";

    String SQL_INNER_DETALLE_PROPUESTA = "INNER JOIN  FECEC_ESTATUS             ON ( FECET_PROPUESTA.ID_ESTATUS = FECEC_ESTATUS.ID_ESTATUS) \n"
            + "INNER JOIN  FECEC_SUBPROGRAMA         ON ( FECET_PROPUESTA.ID_SUBPROGRAMA = FECEC_SUBPROGRAMA.ID_SUBPROGRAMA) \n"
            + "INNER JOIN  FECET_CONTRIBUYENTE       ON ( FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE)  \n"
            + "INNER JOIN  FECEC_METODO              ON ( FECET_PROPUESTA.ID_METODO = FECEC_METODO.ID_METODO) \n"
            + "INNER JOIN  FECEC_SECTOR              ON ( FECET_PROPUESTA.ID_SECTOR = FECEC_SECTOR.ID_SECTOR)  \n"
            + "INNER JOIN  FECEC_TIPO_PROPUESTA      ON ( FECET_PROPUESTA.ID_TIPO_PROPUESTA = FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA) \n"
            + "INNER JOIN  FECEC_CAUSA_PROGRAMACION  ON ( FECET_PROPUESTA.ID_CAUSA_PROGRAMACION = FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION) \n"
            + "LEFT  JOIN  FECEC_REVISION            ON ( FECET_PROPUESTA.ID_REVISION = FECEC_REVISION.ID_REVISION)\n"
            + "INNER JOIN  FECET_DOC_EXPEDIENTE      ON ( FECET_PROPUESTA.ID_PROPUESTA = FECET_DOC_EXPEDIENTE.ID_PROPUESTA)\n"
            + "LEFT  JOIN  FECET_IMPUESTO            ON ( FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA)\n"
            + "LEFT  JOIN  FECEC_TIPO_IMPUESTO       ON ( FECET_IMPUESTO.ID_TIPO_IMPUESTO = FECEC_TIPO_IMPUESTO.ID_TIPO_IMPUESTO)\n"
            + "LEFT  JOIN  FECEC_CONCEPTOS           ON ( FECET_IMPUESTO.ID_CONCEPTO = FECEC_CONCEPTOS.ID_CONCEPTO)\n"
            + "LEFT  JOIN FECET_INSUMO ON ( FECET_PROPUESTA.ID_INSUMO = FECET_INSUMO.ID_INSUMO)";

    String SQL_INNER_DETALLE_CONSULTA_ADMINISTRATIVA = "INNER JOIN  FECEC_ESTATUS             ON ( FECET_PROPUESTA.ID_ESTATUS = FECEC_ESTATUS.ID_ESTATUS) \n"
            + "INNER JOIN  FECEC_SUBPROGRAMA         ON ( FECET_PROPUESTA.ID_SUBPROGRAMA = FECEC_SUBPROGRAMA.ID_SUBPROGRAMA) \n"
            + "INNER JOIN  FECET_CONTRIBUYENTE       ON ( FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE)  \n"
            + "INNER JOIN  FECEC_METODO              ON ( FECET_PROPUESTA.ID_METODO = FECEC_METODO.ID_METODO) \n"
            + "INNER JOIN  FECEC_SECTOR              ON ( FECET_PROPUESTA.ID_SECTOR = FECEC_SECTOR.ID_SECTOR)  \n"
            + "INNER JOIN  FECEC_TIPO_PROPUESTA      ON ( FECET_PROPUESTA.ID_TIPO_PROPUESTA = FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA) \n"
            + "INNER JOIN  FECEC_CAUSA_PROGRAMACION  ON ( FECET_PROPUESTA.ID_CAUSA_PROGRAMACION = FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION) \n"
            + "LEFT  JOIN  FECEC_REVISION            ON ( FECET_PROPUESTA.ID_REVISION = FECEC_REVISION.ID_REVISION)\n"
            + "INNER JOIN  FECET_DOC_EXPEDIENTE      ON ( FECET_PROPUESTA.ID_PROPUESTA = FECET_DOC_EXPEDIENTE.ID_PROPUESTA)\n"
            + "LEFT  JOIN  FECET_IMPUESTO            ON ( FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA AND FECET_IMPUESTO.FECHA_BAJA IS NULL AND FECET_IMPUESTO.ID_RETROALIMENTACION IS NULL) \n "
            + "LEFT  JOIN  FECEC_TIPO_IMPUESTO       ON ( FECET_IMPUESTO.ID_TIPO_IMPUESTO = FECEC_TIPO_IMPUESTO.ID_TIPO_IMPUESTO)\n"
            + "LEFT  JOIN  FECEC_CONCEPTOS           ON ( FECET_IMPUESTO.ID_CONCEPTO = FECEC_CONCEPTOS.ID_CONCEPTO) \n";

    String SQL_INNER_DETALLE_CAMBIO_METODO_PROPUESTA = "INNER JOIN  FECEC_ESTATUS             ON ( FECET_PROPUESTA.ID_ESTATUS = FECEC_ESTATUS.ID_ESTATUS) \n"
            + "INNER JOIN  FECEC_SUBPROGRAMA         ON ( FECET_PROPUESTA.ID_SUBPROGRAMA = FECEC_SUBPROGRAMA.ID_SUBPROGRAMA) \n"
            + "INNER JOIN  FECET_CONTRIBUYENTE       ON ( FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE)  \n"
            + "INNER JOIN  FECEC_METODO              ON ( FECET_PROPUESTA.ID_METODO = FECEC_METODO.ID_METODO) \n"
            + "INNER JOIN  FECEC_SECTOR              ON ( FECET_PROPUESTA.ID_SECTOR = FECEC_SECTOR.ID_SECTOR)  \n"
            + "INNER JOIN  FECEC_TIPO_PROPUESTA      ON ( FECET_PROPUESTA.ID_TIPO_PROPUESTA = FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA) \n"
            + "INNER JOIN  FECEC_CAUSA_PROGRAMACION  ON ( FECET_PROPUESTA.ID_CAUSA_PROGRAMACION = FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION) \n"
            + "LEFT  JOIN  FECEC_REVISION            ON ( FECET_PROPUESTA.ID_REVISION = FECEC_REVISION.ID_REVISION)\n"
            + "INNER JOIN  FECET_DOC_EXPEDIENTE      ON ( FECET_PROPUESTA.ID_PROPUESTA = FECET_DOC_EXPEDIENTE.ID_PROPUESTA)\n"
            + "LEFT  JOIN  FECET_IMPUESTO            ON ( FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA)\n"
            + "LEFT  JOIN  FECEC_TIPO_IMPUESTO       ON ( FECET_IMPUESTO.ID_TIPO_IMPUESTO = FECEC_TIPO_IMPUESTO.ID_TIPO_IMPUESTO)\n"
            + "INNER  JOIN  FECET_ORDEN      ON (FECET_ORDEN.ID_PROPUESTA = FECET_PROPUESTA.ID_PROPUESTA)\n"
            + "INNER  JOIN  FECET_CAMBIO_METODO      ON (FECET_CAMBIO_METODO.ID_ORDEN_ORIGEN = FECET_ORDEN.ID_ORDEN)";

    String SQL_DETALLE_PROPUESTA_HEDER = new StringBuilder()
            .append("SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE,\n")
            .append("FECET_PROPUESTA.ID_SUBPROGRAMA, FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION,\n")
            .append("FECET_PROPUESTA.ID_TIPO_PROPUESTA, FECET_PROPUESTA.ID_CAUSA_PROGRAMACION, FECET_PROPUESTA.ID_SECTOR,\n")
            .append("FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO, \n")
            .append("FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME,  FECET_PROPUESTA.PRIORIDAD,  \n")
            .append("FECET_PROPUESTA.FECHA_CREACION, FECET_PROPUESTA.FECHA_BAJA, FECET_PROPUESTA.RFC_CREACION, \n")
            .append("FECET_PROPUESTA.RFC_ADMINISTRADOR, FECET_PROPUESTA.RFC_SUBADMINISTRADOR, FECET_PROPUESTA.ID_ESTATUS,   \n")
            .append("FECET_PROPUESTA.RFC_AUDITOR, FECET_PROPUESTA.RFC_FIRMANTE, FECET_PROPUESTA.INFORME_PRESENTACION,    \n")
            .append("FECET_PROPUESTA.ID_INSUMO, FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE AS CONTRI_ID, FECET_CONTRIBUYENTE.RFC AS CONTRI_RFC, \n")
            .append("FECET_CONTRIBUYENTE.NOMBRE AS CONTRI_NOMBRE, FECET_CONTRIBUYENTE.REGIMEN AS CONTRI_REGIMEN, FECET_CONTRIBUYENTE.SITUACION  AS CONTRI_SITUACION,    \n")
            .append("FECET_CONTRIBUYENTE.TIPO  AS CONTRI_TIPO, FECET_CONTRIBUYENTE.SITUACION_DOMICILIO  AS CONTRI_SITUACION_DOMICILIO, \n")
            .append("FECET_CONTRIBUYENTE.DOMICILIO_FISCAL  AS CONTRI_DOMICILIO_FISCAL, FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE  AS CONTRI_ACTIVIDAD_PREPONDERANTE,    \n")
            .append("FECET_CONTRIBUYENTE.ENTIDAD  AS CONTRI_ENTIDAD, FECEC_ESTATUS.ID_ESTATUS, FECEC_ESTATUS.DESCRIPCION, \n")
            .append("FECEC_ESTATUS.DESCRIPCION AS DESCRIPCION_ESTATUS, FECEC_ESTATUS.MODULO, FECEC_SUBPROGRAMA.ID_SUBPROGRAMA AS SUBPROGRAMA_ID,    \n")
            .append("FECEC_SUBPROGRAMA.CLAVE AS SUBPROGRAMA_CLAVE, FECEC_SUBPROGRAMA.DESCRIPCION AS DESCRIPCION_SUBPROGRAMA, FECEC_METODO.ID_METODO AS METODO_ID, \n")
            .append("FECEC_METODO.ABREVIATURA AS METODO_ABREVIATURA, FECEC_METODO.NOMBRE AS NOMBRE_METODO, FECEC_SECTOR.ID_SECTOR, \n")
            .append("FECEC_SECTOR.DESCRIPCION AS DESCRIPCION_SECTOR, FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA, FECEC_TIPO_PROPUESTA.DESCRIPCION AS DESCRIPCION_TIPO_PROPUESTA, \n")
            .append("FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION, FECEC_CAUSA_PROGRAMACION.DESCRIPCION AS DESCRIPCION_CAUSA_PROGRAMACION,  \n")
            .append("FECEC_REVISION.ID_REVISION, FECEC_REVISION.DESCRIPCION AS DESCRIPCION_REVISION, FECET_DOC_EXPEDIENTE.ID_DOC_EXPEDIENTE AS ID_DOC,\n")
            .append("FECET_DOC_EXPEDIENTE.RUTA_ARCHIVO AS RUTA_ARCHIVO, FECET_DOC_EXPEDIENTE.FECHA_CREACION AS FECHA_CREACION_ARCHIVO, FECET_IMPUESTO.ID_IMPUESTO AS ID_IMPUESTO,\n")
            .append("FECET_IMPUESTO.ID_TIPO_IMPUESTO AS ID_TIPO_IMPUESTO, FECET_IMPUESTO.MONTO AS IMPUESTO_MONTO,\n")
            .append("FECET_IMPUESTO.FECHA_BAJA AS IMPUESTO_FECHA_BAJA, FECET_IMPUESTO.ID_CONCEPTO AS ID_CONCEPTO,\n")
            .append("FECEC_TIPO_IMPUESTO.ID_TIPO_IMPUESTO AS ID_TIPO_IMPUESTO, FECEC_TIPO_IMPUESTO.DESCRIPCION AS IMPUESTO_DESCRIPCION,\n")
            .append("FECEC_TIPO_IMPUESTO.ABREVIATURA AS IMPUESTO_ABREVIATURA,\n")
            .append("FECEC_CONCEPTOS.DESCRIPCION AS CONCEPTO_DESCRIPCION, FECET_INSUMO.ID_UNIDAD_ADMINISTRATIVA\n").append("FROM ").append(NAME_TABLE)
            .append(SALTO_LINEA).toString();

    String SQL_HEDER_CONSULTA_ADMINISTRATIVA = new StringBuilder()
            .append("SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, FECET_PROPUESTA.ID_SUBPROGRAMA,\n")
            .append("FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION, FECET_PROPUESTA.ID_TIPO_PROPUESTA, FECET_PROPUESTA.ID_CAUSA_PROGRAMACION,\n")
            .append("FECET_PROPUESTA.ID_SECTOR, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO, \n")
            .append("FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.PRIORIDAD, FECET_PROPUESTA.FECHA_CREACION, \n")
            .append("FECET_PROPUESTA.FECHA_BAJA, FECET_PROPUESTA.RFC_CREACION, FECET_PROPUESTA.RFC_ADMINISTRADOR,  FECET_PROPUESTA.RFC_SUBADMINISTRADOR,\n")
            .append("FECET_PROPUESTA.ID_ESTATUS, FECET_PROPUESTA.RFC_AUDITOR,  FECET_PROPUESTA.RFC_FIRMANTE, FECET_PROPUESTA.INFORME_PRESENTACION,    \n")
            .append("FECET_PROPUESTA.ID_INSUMO, FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE AS CONTRI_ID, FECET_CONTRIBUYENTE.RFC AS CONTRI_RFC, \n")
            .append("FECET_CONTRIBUYENTE.NOMBRE AS CONTRI_NOMBRE, FECET_CONTRIBUYENTE.REGIMEN AS CONTRI_REGIMEN, FECET_CONTRIBUYENTE.SITUACION  AS CONTRI_SITUACION,    \n")
            .append("FECET_CONTRIBUYENTE.TIPO  AS CONTRI_TIPO, FECET_CONTRIBUYENTE.SITUACION_DOMICILIO  AS CONTRI_SITUACION_DOMICILIO, FECET_CONTRIBUYENTE.DOMICILIO_FISCAL  AS CONTRI_DOMICILIO_FISCAL, \n")
            .append("FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE  AS CONTRI_ACTIVIDAD_PREPONDERANTE, FECET_CONTRIBUYENTE.ENTIDAD  AS CONTRI_ENTIDAD,  FECEC_ESTATUS.ID_ESTATUS,    \n")
            .append("FECEC_ESTATUS.DESCRIPCION, FECEC_ESTATUS.DESCRIPCION AS DESCRIPCION_ESTATUS, FECEC_ESTATUS.MODULO,  FECEC_SUBPROGRAMA.ID_SUBPROGRAMA AS SUBPROGRAMA_ID, FECEC_SUBPROGRAMA.CLAVE AS SUBPROGRAMA_CLAVE, \n")
            .append("FECEC_SUBPROGRAMA.DESCRIPCION AS DESCRIPCION_SUBPROGRAMA, FECEC_METODO.ID_METODO AS METODO_ID, FECEC_METODO.ABREVIATURA AS METODO_ABREVIATURA,   \n")
            .append("FECEC_METODO.NOMBRE AS NOMBRE_METODO,  FECEC_SECTOR.ID_SECTOR, FECEC_SECTOR.DESCRIPCION AS DESCRIPCION_SECTOR, FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA,  \n")
            .append("FECEC_TIPO_PROPUESTA.DESCRIPCION AS DESCRIPCION_TIPO_PROPUESTA, FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION, FECEC_CAUSA_PROGRAMACION.DESCRIPCION AS DESCRIPCION_CAUSA_PROGRAMACION,  \n")
            .append("FECEC_REVISION.ID_REVISION, FECEC_REVISION.DESCRIPCION AS DESCRIPCION_REVISION, FECET_DOC_EXPEDIENTE.ID_DOC_EXPEDIENTE AS ID_DOC,\n")
            .append("FECET_DOC_EXPEDIENTE.RUTA_ARCHIVO AS RUTA_ARCHIVO, FECET_DOC_EXPEDIENTE.FECHA_CREACION AS FECHA_CREACION_ARCHIVO, FECET_IMPUESTO.ID_IMPUESTO AS ID_IMPUESTO,\n")
            .append("FECET_IMPUESTO.ID_TIPO_IMPUESTO AS ID_TIPO_IMPUESTO, FECET_IMPUESTO.MONTO AS IMPUESTO_MONTO, FECET_IMPUESTO.FECHA_BAJA       AS IMPUESTO_FECHA_BAJA,\n")
            .append("FECET_IMPUESTO.ID_CONCEPTO AS ID_CONCEPTO, FECEC_TIPO_IMPUESTO.ID_TIPO_IMPUESTO AS ID_TIPO_IMPUESTO, FECEC_TIPO_IMPUESTO.DESCRIPCION AS IMPUESTO_DESCRIPCION,\n")
            .append("FECEC_TIPO_IMPUESTO.ABREVIATURA AS IMPUESTO_ABREVIATURA, FECEC_CONCEPTOS.DESCRIPCION AS CONCEPTO_DESCRIPCION\n")
            .append("FROM FECET_PROPUESTA \n").toString();

    String SQL_DETALLE_PROPUESTA_CAMBIO_METODO_HEDER = "SELECT FECET_PROPUESTA.ID_PROPUESTA,\n"
            + "FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, \n" + "FECET_PROPUESTA.ID_SUBPROGRAMA,\n"
            + "FECET_PROPUESTA.ID_METODO,\n" + "FECET_PROPUESTA.ID_REVISION,\n" + "FECET_PROPUESTA.ID_TIPO_PROPUESTA,\n"
            + "FECET_PROPUESTA.ID_CAUSA_PROGRAMACION,\n" + "FECET_PROPUESTA.ID_SECTOR,\n"
            + "FECET_PROPUESTA.ID_REGISTRO,\n" + "FECET_PROPUESTA.FECHA_INICIO_PERIODO,\n"
            + "FECET_PROPUESTA.FECHA_FIN_PERIODO, \n" + "FECET_PROPUESTA.FECHA_PRESENTACION, \n"
            + "FECET_PROPUESTA.FECHA_INFORME, \n" + "FECET_PROPUESTA.PRIORIDAD,  \n"
            + "FECET_PROPUESTA.FECHA_CREACION, \n" + "FECET_PROPUESTA.FECHA_BAJA, \n"
            + "FECET_PROPUESTA.RFC_CREACION, \n" + "FECET_PROPUESTA.RFC_ADMINISTRADOR, \n"
            + "FECET_PROPUESTA.RFC_SUBADMINISTRADOR,\n" + "FECET_PROPUESTA.ID_ESTATUS,   \n"
            + "FECET_PROPUESTA.RFC_AUDITOR,    \n" + "FECET_PROPUESTA.RFC_FIRMANTE, \n"
            + "FECET_PROPUESTA.INFORME_PRESENTACION,    \n" + "FECET_PROPUESTA.ID_INSUMO, \n"
            + "FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE AS CONTRI_ID,    \n" + "FECET_CONTRIBUYENTE.RFC AS CONTRI_RFC, \n"
            + "FECET_CONTRIBUYENTE.NOMBRE AS CONTRI_NOMBRE,    \n"
            + "FECET_CONTRIBUYENTE.REGIMEN AS CONTRI_REGIMEN,  \n"
            + "FECET_CONTRIBUYENTE.SITUACION  AS CONTRI_SITUACION,    \n"
            + "FECET_CONTRIBUYENTE.TIPO  AS CONTRI_TIPO, \n"
            + "FECET_CONTRIBUYENTE.SITUACION_DOMICILIO  AS CONTRI_SITUACION_DOMICILIO,    \n"
            + "FECET_CONTRIBUYENTE.DOMICILIO_FISCAL  AS CONTRI_DOMICILIO_FISCAL, \n"
            + "FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE  AS CONTRI_ACTIVIDAD_PREPONDERANTE,    \n"
            + "FECET_CONTRIBUYENTE.ENTIDAD  AS CONTRI_ENTIDAD,  \n" + "FECEC_ESTATUS.ID_ESTATUS,    \n"
            + "FECEC_ESTATUS.DESCRIPCION, \n" + "FECEC_ESTATUS.DESCRIPCION AS DESCRIPCION_ESTATUS,    \n"
            + "FECEC_ESTATUS.MODULO, \n" + "FECEC_SUBPROGRAMA.ID_SUBPROGRAMA AS SUBPROGRAMA_ID,    \n"
            + "FECEC_SUBPROGRAMA.CLAVE AS SUBPROGRAMA_CLAVE, \n"
            + "FECEC_SUBPROGRAMA.DESCRIPCION AS DESCRIPCION_SUBPROGRAMA,  \n"
            + "FECEC_METODO.ID_METODO AS METODO_ID,  \n" + "FECEC_METODO.ABREVIATURA AS METODO_ABREVIATURA,   \n"
            + "FECEC_METODO.NOMBRE AS NOMBRE_METODO, \n"
            + "FECEC_SECTOR.ID_SECTOR, \n"
            + "FECEC_SECTOR.DESCRIPCION AS DESCRIPCION_SECTOR,    \n" + "FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA,  \n"
            + "FECEC_TIPO_PROPUESTA.DESCRIPCION AS DESCRIPCION_TIPO_PROPUESTA, \n"
            + "FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION, \n"
            + "FECEC_CAUSA_PROGRAMACION.DESCRIPCION AS DESCRIPCION_CAUSA_PROGRAMACION,  \n"
            + "FECEC_REVISION.ID_REVISION,    \n" + "FECEC_REVISION.DESCRIPCION AS DESCRIPCION_REVISION,\n"
            + "FECET_DOC_EXPEDIENTE.ID_DOC_EXPEDIENTE AS ID_DOC,\n"
            + "FECET_DOC_EXPEDIENTE.RUTA_ARCHIVO AS RUTA_ARCHIVO,\n"
            + "FECET_DOC_EXPEDIENTE.FECHA_CREACION AS FECHA_CREACION_ARCHIVO,\n"
            + "FECET_IMPUESTO.ID_IMPUESTO AS ID_IMPUESTO,\n" + "FECET_IMPUESTO.ID_TIPO_IMPUESTO AS ID_TIPO_IMPUESTO,\n"
            + "FECET_IMPUESTO.MONTO            AS IMPUESTO_MONTO,\n"
            + "FECET_IMPUESTO.FECHA_BAJA       AS IMPUESTO_FECHA_BAJA,\n"
            + "FECEC_TIPO_IMPUESTO.ID_TIPO_IMPUESTO AS ID_TIPO_IMPUESTO,\n"
            + "FECEC_TIPO_IMPUESTO.DESCRIPCION      AS IMPUESTO_DESCRIPCION,\n"
            + "FECEC_TIPO_IMPUESTO.ABREVIATURA      AS IMPUESTO_ABREVIATURA,\n"
            + "FECET_ORDEN.ID_ORDEN      AS ID_ORDEN,\n" + "FECET_ORDEN.NUMERO_ORDEN  AS NUMERO_ORDEN,\n"
            + "  FECET_CAMBIO_METODO.ID_METODO_NUEVO as ID_METODO_ORDEN,\n"
            + " (SELECT a.NOMBRE  FROM FECEC_METODO a WHERE a.ID_METODO = FECET_CAMBIO_METODO.ID_METODO_NUEVO) as METODO_DESCRIPCION_ORDEN,\n"
            + " (SELECT b.ABREVIATURA  FROM FECEC_METODO b WHERE b.ID_METODO = FECET_CAMBIO_METODO.ID_METODO_NUEVO) as METODOS_ABREVIATURA_ORDEN\n"
            + "FROM FECET_PROPUESTA \n";

    String SQL_DETALLE_PROPUESTA_FOOTER = " ORDER BY FECET_PROPUESTA.PRIORIDAD";
    String SQL_DETALLE_PROPUESTA_FOOTER_BY_ID = " GROUP BY FECET_PROPUESTA.ID_PROPUESTA,FECET_PROPUESTA.ID_PROPUESTA,\n"
            + "FECET_PROPUESTA.ID_CONTRIBUYENTE, \n FECET_PROPUESTA.ID_ARACE,\n" + "FECET_PROPUESTA.ID_SUBPROGRAMA,\n"
            + "FECET_PROPUESTA.ID_METODO,\n" + "FECET_PROPUESTA.ID_REVISION,\n" + "FECET_PROPUESTA.ID_TIPO_PROPUESTA,\n"
            + "FECET_PROPUESTA.ID_CAUSA_PROGRAMACION,\n" + "FECET_PROPUESTA.ID_SECTOR,\n"
            + "FECET_PROPUESTA.ID_REGISTRO,\n" + "FECET_PROPUESTA.FECHA_INICIO_PERIODO,\n"
            + "FECET_PROPUESTA.FECHA_FIN_PERIODO, \n" + "FECET_PROPUESTA.FECHA_PRESENTACION, \n"
            + "FECET_PROPUESTA.FECHA_INFORME, \n" + "FECET_PROPUESTA.PRIORIDAD,  \n"
            + "FECET_PROPUESTA.FECHA_CREACION, \n" + "FECET_PROPUESTA.FECHA_BAJA, \n"
            + "FECET_PROPUESTA.RFC_CREACION, \n" + "FECET_PROPUESTA.RFC_ADMINISTRADOR, \n"
            + "FECET_PROPUESTA.RFC_SUBADMINISTRADOR,\n" + "FECET_PROPUESTA.ID_ESTATUS,   \n"
            + "FECET_PROPUESTA.RFC_AUDITOR,    \n" + "FECET_PROPUESTA.RFC_FIRMANTE, \n"
            + "FECET_PROPUESTA.INFORME_PRESENTACION,    \n" + "FECET_PROPUESTA.ID_INSUMO, \n"
            + "FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE,    \n" + "FECET_CONTRIBUYENTE.RFC, \n"
            + "FECET_CONTRIBUYENTE.NOMBRE,    \n" + "FECET_CONTRIBUYENTE.REGIMEN,  \n"
            + "FECET_CONTRIBUYENTE.SITUACION,    \n" + "FECET_CONTRIBUYENTE.TIPO, \n"
            + "FECET_CONTRIBUYENTE.SITUACION_DOMICILIO,    \n" + "FECET_CONTRIBUYENTE.DOMICILIO_FISCAL, \n"
            + "FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE,    \n" + "FECET_CONTRIBUYENTE.ENTIDAD,  \n"
            + "FECEC_ESTATUS.ID_ESTATUS,    \n" + "FECEC_ESTATUS.DESCRIPCION, \n" + "FECEC_ESTATUS.DESCRIPCION,    \n"
            + "FECEC_ESTATUS.MODULO, \n" + "FECEC_SUBPROGRAMA.ID_SUBPROGRAMA,    \n" + "FECEC_SUBPROGRAMA.CLAVE, \n"
            + "FECEC_SUBPROGRAMA.DESCRIPCION,    \n" + "FECEC_METODO.ID_METODO,  \n" + "FECEC_METODO.ABREVIATURA,   \n"
            + "FECEC_METODO.NOMBRE, \n" + "FECEC_UNIDAD_ADMINISTRATIVA.ID_UNIDAD_ADMINISTRATIVA AS ID_ARACE,    \n"
            + "FECEC_UNIDAD_ADMINISTRATIVA.NOMBRE,    \n" + "FECEC_SECTOR.ID_SECTOR, \n"
            + "FECEC_SECTOR.DESCRIPCION,    \n" + "FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA,  \n"
            + "FECEC_TIPO_PROPUESTA.DESCRIPCION, \n" + "FECEC_CAUSA_PROGRAMACION.ID_CAUSA_PROGRAMACION, \n"
            + "FECEC_CAUSA_PROGRAMACION.DESCRIPCION,  \n" + "FECEC_REVISION.ID_REVISION,    \n"
            + "FECEC_REVISION.DESCRIPCION,\n" + "FECET_DOC_EXPEDIENTE.ID_DOC_EXPEDIENTE,\n"
            + "FECET_DOC_EXPEDIENTE.RUTA_ARCHIVO,\n" + "FECET_DOC_EXPEDIENTE.FECHA_CREACION,\n"
            + "FECET_IMPUESTO.ID_IMPUESTO,\n" + "FECET_IMPUESTO.ID_TIPO_IMPUESTO,\n" + "FECET_IMPUESTO.MONTO,\n"
            + "FECET_IMPUESTO.PERIODO_INICIAL,\n" + "FECET_IMPUESTO.PERIODO_FINAL,\n" + "FECET_IMPUESTO.FECHA_BAJA,\n"
            + "FECEC_TIPO_IMPUESTO.ID_TIPO_IMPUESTO,\n" + "FECEC_TIPO_IMPUESTO.DESCRIPCION,\n"
            + "FECEC_TIPO_IMPUESTO.ABREVIATURA\n" + "ORDER BY FECET_PROPUESTA.ID_PROPUESTA ";

    String UPDATE_ESTADO_PROPUESTA_BAJA = "UPDATE " + NAME_TABLE
            + " SET ID_ESTATUS = ? , FECHA_BAJA = ? WHERE ID_PROPUESTA = ? ";

    String UPDATE_ESTADO_PROPUESTA = "UPDATE " + NAME_TABLE + " SET ID_ESTATUS = ? WHERE ID_PROPUESTA = ?";

    String SQL_CONDICION_ESTATUS = " FECET_PROPUESTA.ID_ESTATUS IN ( {LST_ESTATUS} ) ";

    String SQL_CONDICION_METODO = " FECEC_METODO.ID_METODO = ? ";
    String SQL_CONDICION_PRIORIDAD = "FECET_PROPUESTA.PRIORIDAD <> ? ";

    String SQL_CONDICION_ARACES = " FECET_PROPUESTA.ID_ARACE IN ( {IDS} )";

    String SQL_CONDICION_ID_ACCION = " AND PROPUESTA_ACCION.ID_ACCION IN ( {ID_ACCION} )";
    String SQL_CONDICION_ID_ACCION_REVISION = " AND PROPUESTA_ACCION.ID_ACCION NOT IN ( {ID_ACCION} )";

    String SQL_CONDICION_RFC_FIRMANTE = " AND FECET_PROPUESTA.RFC_FIRMANTE = ? ";
    String SQL_CONDICION_RFC_AUDITOR = " AND FECET_PROPUESTA.RFC_AUDITOR = ? ";
    String SQL_CONDICION_RFCS_PROGRAMADOR = " AND FECET_PROPUESTA.RFC_CREACION IN ( {RFC_PROGRAMADOR} ) ";
    String SQL_CONDICION_IDS_PROGRAMADOR = " AND FECET_PROPUESTA.ID_PROGRAMADOR IN ( {ID_PROGRAMADOR} ) ";

    String SQL_CONDICION_REGISTRADA = " AND ((FECET_PROPUESTA.RFC_CREACION IN ({RFC_PROGRAMADOR}) AND FECET_PROPUESTA.ID_PROGRAMADOR IS NULL) "
            + " OR (FECET_PROPUESTA.ID_PROGRAMADOR IS NOT NULL AND FECET_PROPUESTA.ID_ARACE IN (19,20) AND FECET_PROPUESTA.RFC_CREACION IN ({RFC_SUBADMINISTRADOR})) "
            + " OR (FECET_PROPUESTA.ID_PROGRAMADOR IN ( {ID_PROGRAMADOR} ) AND FECET_PROPUESTA.ID_ARACE NOT IN (19,20) AND FECET_PROPUESTA.RFC_CREACION IN ({RFC_SUBADMINISTRADOR}))) ";

    String SQL_CONDICION_ENVIADA_ADACE = " AND FECET_PROPUESTA.ID_PROGRAMADOR IS NOT NULL AND FECET_PROPUESTA.ID_ARACE NOT IN (19,20) \n "
            + " AND (FECET_PROPUESTA.RFC_CREACION IN ({RFC_PROGRAMADOR}) AND FECET_PROPUESTA.ID_PROGRAMADOR NOT IN ({ID_PROGRAMADOR}) \n"
            + " OR FECET_PROPUESTA.RFC_CREACION NOT IN ({RFC_PROGRAMADOR}) AND FECET_PROPUESTA.ID_PROGRAMADOR IN ({ID_PROGRAMADOR}))";

    String SQL_CONDICION_RFC_ID_PROPGRAMADOR = " AND (FECET_PROPUESTA.RFC_CREACION IN ( {RFC_PROGRAMADOR} ) OR FECET_PROPUESTA.ID_PROGRAMADOR IN ( {ID_PROGRAMADOR} ) )";

    String ID_PROGRAMADOR_NULL = " AND FECET_PROPUESTA.ID_PROGRAMADOR IS NULL \n";
    String ID_PROGRAMADOR_NOT_NULL = " AND FECET_PROPUESTA.ID_PROGRAMADOR IS NOT NULL \n";
    String GABINETE_2 = " AND FECET_PROPUESTA.ID_METODO = 2 \n ";
    String SQL_CONDICION_SELECTOR_ESTATUS = "\n  AND (FECET_PROPUESTA.ID_ESTATUS IN ( {LST_ESTATUS} ) OR (FECET_PROPUESTA.ID_ESTATUS = 49 AND FECET_PROPUESTA.ID_METODO <> 2))";
    String SQL_ASIGNADA_ESTATUS = "\n AND ((FECET_PROPUESTA.ID_ESTATUS IN ({LST_ESTATUS})) OR (FECET_PROPUESTA.ID_ESTATUS = 68 AND FECET_PROPUESTA.ID_METODO <> 2 AND FECET_PROPUESTA.ID_PROGRAMADOR IS NULL))";
    String SQL_ASIGNADA_ESTATUS_ADACE = "\n AND ((FECET_PROPUESTA.ID_ESTATUS IN ({LST_ESTATUS})) OR (FECET_PROPUESTA.ID_ESTATUS = 68 AND FECET_PROPUESTA.ID_METODO <> 2 AND FECET_PROPUESTA.ID_PROGRAMADOR IS NULL) OR (FECET_PROPUESTA.ID_ESTATUS = 49 AND FECET_PROPUESTA.ID_METODO <> 2))";

    String ID_TEMPLATE = "{IDS}";
    String LST_ESTATUS = "{LST_ESTATUS}";
    String ID_ACCION = "{ID_ACCION}";
    String RFC_PROGRAMADOR = "{RFC_PROGRAMADOR}";
    String RFC_SUBADMINISTRADOR = "{RFC_SUBADMINISTRADOR}";
    String IDS_PROGRAMADOR = "{ID_PROGRAMADOR}";

    String SQL_SELECT = "SELECT " + COLUMNAS_PRIMARIAS + "FECHA_INICIO_PERIODO,\n" + "FECHA_FIN_PERIODO,\n"
            + "FECHA_PRESENTACION,\n" + "FECHA_INFORME,\n" + "PRIORIDAD,\n" + "FECHA_CREACION,\n" + "FECHA_BAJA,\n"
            + "RFC_CREACION,\n" + "RFC_ADMINISTRADOR,\n" + "RFC_SUBADMINISTRADOR,\n" + "ID_ESTATUS,\n"
            + "RFC_FIRMANTE,\n" + "RFC_AUDITOR,\n" + "INFORME_PRESENTACION,\n" + "ID_INSUMO,\n"
            + "ID_REGISTRO_INSUMO,\n"
            + "(SELECT a.NOMBRE FROM FECEC_METODO a WHERE a.ID_METODO = FECET_PROPUESTA.ID_METODO) AS DESCRIPCION_METODO, "
            + "(SELECT b.DESCRIPCION FROM FECEC_SUBPROGRAMA b WHERE b.ID_SUBPROGRAMA = FECET_PROPUESTA.ID_SUBPROGRAMA) AS DESCRIPCION_SUBPROGRAMA, "
            + "(SELECT c.DESCRIPCION FROM FECEC_TIPO_PROPUESTA c WHERE c.ID_TIPO_PROPUESTA = FECET_PROPUESTA.ID_TIPO_PROPUESTA) AS DESCRIPCION_TIPO_PROPUESTA, "
            + "(SELECT d.DESCRIPCION FROM FECEC_REVISION d WHERE d.ID_REVISION = FECET_PROPUESTA.ID_REVISION) AS DESCRIPCION_REVISION, "
            + "(SELECT e.DESCRIPCION FROM FECEC_CAUSA_PROGRAMACION e WHERE e.ID_CAUSA_PROGRAMACION = FECET_PROPUESTA.ID_CAUSA_PROGRAMACION) AS DESCRIPCION_CAUSA_PROGRAMACION, "
            + "(SELECT p.DESCRIPCION FROM FECEC_SECTOR p WHERE p.ID_SECTOR = FECET_PROPUESTA.ID_SECTOR) AS SECTOR_DESCRIPCION "
            + "FROM ";

    String SQL_GRUP_BY_PROPUESTAS = "GROUP BY FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, FECET_PROPUESTA.ID_SUBPROGRAMA,\n"
            + "FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION, FECET_PROPUESTA.ID_TIPO_PROPUESTA, FECET_PROPUESTA.ID_CAUSA_PROGRAMACION,\n"
            + "FECET_PROPUESTA.ID_SECTOR, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO,\n"
            + "FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.PRIORIDAD, FECET_PROPUESTA.FECHA_CREACION,\n"
            + "FECET_PROPUESTA.FECHA_BAJA, FECET_PROPUESTA.RFC_CREACION, FECET_PROPUESTA.RFC_ADMINISTRADOR, FECET_PROPUESTA.RFC_SUBADMINISTRADOR,\n"
            + "FECET_PROPUESTA.ID_ESTATUS, FECET_PROPUESTA.RFC_FIRMANTE, FECET_PROPUESTA.RFC_AUDITOR, FECET_PROPUESTA.INFORME_PRESENTACION,\n"
            + "FECET_PROPUESTA.ID_INSUMO, FECET_PROPUESTA.ID_REGISTRO_INSUMO, FECEC_SUBPROGRAMA.CLAVE, FECEC_SUBPROGRAMA.DESCRIPCION, FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE,\n"
            + "FECET_CONTRIBUYENTE.RFC, FECET_CONTRIBUYENTE.NOMBRE, FECET_CONTRIBUYENTE.REGIMEN, FECET_CONTRIBUYENTE.SITUACION, FECET_CONTRIBUYENTE.TIPO,\n"
            + "FECET_CONTRIBUYENTE.SITUACION_DOMICILIO, FECET_CONTRIBUYENTE.DOMICILIO_FISCAL, FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE,\n"
            + "FECET_CONTRIBUYENTE.ENTIDAD, FECEC_SECTOR.ID_SECTOR, FECEC_SECTOR.DESCRIPCION, FECEC_METODO.ABREVIATURA, FECEC_ESTATUS.DESCRIPCION, FECEC_ESTATUS.MODULO, "
            + " FECEC_TIPO_PROPUESTA.DESCRIPCION";

    String SQL_CONDICION = " INNER JOIN FECEC_SUBPROGRAMA ON FECEC_SUBPROGRAMA.ID_SUBPROGRAMA = FECET_PROPUESTA.ID_SUBPROGRAMA \n";
    String SQL_CONDICION2 = " INNER JOIN FECET_CONTRIBUYENTE ON FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE = FECET_PROPUESTA.ID_CONTRIBUYENTE \n";
    String SQL_CONDICION3 = " INNER JOIN FECEC_SECTOR ON FECEC_SECTOR.ID_SECTOR = FECET_PROPUESTA.ID_SECTOR \n";
    String SQL_CONDICION4 = " LEFT JOIN FECET_IMPUESTO ON FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA \n";
    String SQL_CONDICION5 = " INNER JOIN FECEC_METODO ON FECEC_METODO.ID_METODO = FECET_PROPUESTA.ID_METODO \n";
    String SQL_CONDICION6 = " INNER JOIN FECEC_ESTATUS ON FECEC_ESTATUS.ID_ESTATUS = FECET_PROPUESTA.ID_ESTATUS \n";

    String INSERT_RESUMEN_MASIVA = "INSERT INTO fecet_masiva (id_masiva, id_carga, total_registros, fecha_carga, id_origen) "
            + "VALUES(FECEQ_MASIVA.NEXTVAL, ?, ?, SYSDATE, ?)";

    String SQL_ANTECEDENTES_AGACE_HEDER = "SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, FECET_PROPUESTA.ID_SUBPROGRAMA, FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION, FECET_PROPUESTA.ID_TIPO_PROPUESTA, \n"
            + "FECET_PROPUESTA.ID_CAUSA_PROGRAMACION, FECET_PROPUESTA.ID_SECTOR, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO, FECET_PROPUESTA.FECHA_PRESENTACION, \n"
            + "FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.PRIORIDAD, FECET_PROPUESTA.FECHA_CREACION, FECET_PROPUESTA.FECHA_BAJA, FECET_PROPUESTA.RFC_CREACION, FECET_PROPUESTA.RFC_ADMINISTRADOR,\n"
            + "FECET_PROPUESTA.RFC_SUBADMINISTRADOR, FECET_PROPUESTA.ID_ESTATUS, FECET_PROPUESTA.RFC_FIRMANTE, FECET_PROPUESTA.RFC_AUDITOR, FECET_PROPUESTA.INFORME_PRESENTACION, FECET_PROPUESTA.ID_INSUMO, \n"
            + "FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE, FECET_CONTRIBUYENTE.RFC, FECET_CONTRIBUYENTE.NOMBRE, FECET_CONTRIBUYENTE.REGIMEN, FECET_CONTRIBUYENTE.SITUACION, FECET_CONTRIBUYENTE.TIPO, \n"
            + "FECET_CONTRIBUYENTE.SITUACION_DOMICILIO, FECET_CONTRIBUYENTE.DOMICILIO_FISCAL, FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE, FECET_CONTRIBUYENTE.ENTIDAD, FECEC_ESTATUS.ID_ESTATUS, FECEC_ESTATUS.DESCRIPCION,\n"
            + "FECEC_ESTATUS.DESCRIPCION AS DESCRIPCION_ESTATUS, FECEC_ESTATUS.MODULO, FECEC_SUBPROGRAMA.ID_SUBPROGRAMA, FECEC_SUBPROGRAMA.CLAVE, FECEC_SUBPROGRAMA.DESCRIPCION DESCRIPCION_SUBPROGRAMA, FECEC_METODO.ID_METODO, FECEC_METODO.ABREVIATURA, FECEC_METODO.NOMBRE AS NOMBRE_METODO,\n"
            + "FECET_PROPUESTA.ID_REGISTRO_INSUMO\n" + FROM_TABLE;

    String SQL_ANTECEDENTES_AGACE_INNER = "INNER JOIN FECEC_ESTATUS ON ( FECET_PROPUESTA.ID_ESTATUS = FECEC_ESTATUS.ID_ESTATUS) \n"
            + "INNER JOIN FECEC_SUBPROGRAMA ON ( FECET_PROPUESTA.ID_SUBPROGRAMA = FECEC_SUBPROGRAMA.ID_SUBPROGRAMA)\n"
            + "INNER JOIN FECET_CONTRIBUYENTE ON ( FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE) \n"
            + "INNER JOIN FECEC_METODO ON ( FECET_PROPUESTA.ID_METODO = FECEC_METODO.ID_METODO) ";

    String SQL_ANTECEDENTES_AGACE_WHERE = " WHERE  FECET_CONTRIBUYENTE.RFC = ? \n"
            + "AND FECET_PROPUESTA.FECHA_INICIO_PERIODO >= ? \n" + "AND FECET_PROPUESTA.FECHA_FIN_PERIODO <= ? \n"
            + "AND FECET_PROPUESTA.ID_ESTATUS NOT IN (?,?,?,?,?)";

    String SQL_ANTECEDENTES_AGACE_WHERE_PERIODO_EXACTO = " WHERE  FECET_CONTRIBUYENTE.RFC = ? \n"
            + "AND TRUNC(FECET_PROPUESTA.FECHA_INICIO_PERIODO) = TRUNC(?) \n"
            + "AND FECET_PROPUESTA.FECHA_FIN_PERIODO = TRUNC(?) \n"
            + "AND FECET_PROPUESTA.ID_ESTATUS NOT IN (?,?,?,?,?)";

    String SQL_ANTECEDENTES_PROPUESTA_HEDER = "SELECT pro.ID_PROPUESTA, pro.ID_CONTRIBUYENTE, pro.ID_ARACE, pro.ID_SUBPROGRAMA, pro.ID_METODO, pro.ID_REVISION, pro.ID_TIPO_PROPUESTA,\n"
            + "pro.ID_CAUSA_PROGRAMACION, pro.ID_SECTOR, pro.ID_REGISTRO, pro.FECHA_INICIO_PERIODO, pro.FECHA_FIN_PERIODO, pro.FECHA_PRESENTACION,\n"
            + "pro.FECHA_INFORME, pro.PRIORIDAD, pro.FECHA_CREACION, pro.FECHA_BAJA, pro.RFC_CREACION, pro.RFC_ADMINISTRADOR,\n"
            + "pro.RFC_SUBADMINISTRADOR, pro.ID_ESTATUS, pro.RFC_FIRMANTE, pro.RFC_AUDITOR, pro.INFORME_PRESENTACION, pro.ID_INSUMO\n"
            + "FROM FECET_PROPUESTA pro \n";
    String SQL_ANTECEDENTES_PROPUESTA_INNER = "INNER JOIN FECET_CONTRIBUYENTE contr ON (pro.ID_CONTRIBUYENTE = contr.ID_CONTRIBUYENTE) \n";

    String SQL_ANTECEDENTES_PROPUESTA_WHERE = "WHERE CONTRIBUYENTE.RFC = ?\n" + "AND PROPUESTA.ID_ESTATUS NOT IN (?,?,?,?,?) \n";

    String SQL_DETALLE_OFICIO_HEDER = "SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, FECET_PROPUESTA.ID_SUBPROGRAMA, FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION, FECET_PROPUESTA.ID_TIPO_PROPUESTA, \n"
            + "FECET_PROPUESTA.ID_CAUSA_PROGRAMACION, FECET_PROPUESTA.ID_SECTOR, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO, FECET_PROPUESTA.FECHA_PRESENTACION,  FECET_PROPUESTA.FECHA_INFORME,  FECET_PROPUESTA.PRIORIDAD, \n"
            + "FECET_PROPUESTA.FECHA_CREACION,  FECET_PROPUESTA.FECHA_BAJA,  FECET_PROPUESTA.RFC_CREACION, FECET_PROPUESTA.RFC_ADMINISTRADOR,  FECET_PROPUESTA.RFC_SUBADMINISTRADOR, FECET_PROPUESTA.ID_ESTATUS,  FECET_PROPUESTA.RFC_FIRMANTE,  FECET_PROPUESTA.RFC_AUDITOR, \n"
            + "FECET_PROPUESTA.INFORME_PRESENTACION,  FECET_PROPUESTA.ID_INSUMO, FECET_PROPUESTA.ID_REGISTRO_INSUMO, FECET_PROPUESTA.ID_ORIGEN, FECET_PROPUESTA.CONSECUTIVO_ANO, FECET_PROPUESTA.ID_PROGRAMADOR, FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE,  FECET_CONTRIBUYENTE.RFC,  FECET_CONTRIBUYENTE.NOMBRE, FECET_CONTRIBUYENTE.REGIMEN,  FECET_CONTRIBUYENTE.SITUACION,  FECET_CONTRIBUYENTE.TIPO, \n"
            + "FECET_CONTRIBUYENTE.SITUACION_DOMICILIO,  FECET_CONTRIBUYENTE.DOMICILIO_FISCAL, FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE,  FECET_CONTRIBUYENTE.ENTIDAD,  FECEC_SUBPROGRAMA.ID_SUBPROGRAMA,  FECEC_SUBPROGRAMA.CLAVE,  FECEC_SUBPROGRAMA.DESCRIPCION, \n"
            + "FECEC_SUBPROGRAMA.DESCRIPCION AS DESCRIPCION_SUBPROGRAMA,  FECEC_SECTOR.ID_SECTOR, FECEC_SECTOR.DESCRIPCION AS DESCRIPCION_SECTOR,  FECEC_ESTATUS.ID_ESTATUS, FECEC_ESTATUS.DESCRIPCION DESCRIPCION_ESTATUS,  FECEC_ESTATUS.MODULO, FECEC_ESTATUS.ID_MODULO,  \n"
            + "FECEC_REVISION.DESCRIPCION DESCRIPCION_REVISION \n"
            + "FROM FECET_PROPUESTA \n";

    String SQL_DETALLE_OFICIO_BODY = " INNER JOIN FECET_CONTRIBUYENTE ON (  FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE)\n"
            + " INNER JOIN FECEC_SUBPROGRAMA ON ( FECET_PROPUESTA.ID_SUBPROGRAMA =  FECEC_SUBPROGRAMA.ID_SUBPROGRAMA)\n"
            + " INNER JOIN FECEC_SECTOR ON (  FECET_PROPUESTA.ID_SECTOR = FECEC_SECTOR.ID_SECTOR)\n"
            + " INNER JOIN FECEC_ESTATUS ON (  FECET_PROPUESTA.ID_ESTATUS = FECEC_ESTATUS.ID_ESTATUS)\n"
            + " LEFT JOIN FECEC_REVISION ON FECEC_REVISION.ID_REVISION = FECET_PROPUESTA.ID_REVISION \n"
            + " WHERE FECET_PROPUESTA.ID_REGISTRO = ?";

    String SQL_INSUMOS_NO_ASIGNADOS = "SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, FECET_PROPUESTA.ID_SUBPROGRAMA, FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION, FECET_PROPUESTA.ID_TIPO_PROPUESTA, FECET_PROPUESTA.ID_CAUSA_PROGRAMACION, \n"
            + "FECET_PROPUESTA.ID_SECTOR, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO, FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.PRIORIDAD, FECET_PROPUESTA.FECHA_CREACION, FECET_PROPUESTA.FECHA_BAJA, \n"
            + "FECET_PROPUESTA.RFC_CREACION, FECET_PROPUESTA.RFC_ADMINISTRADOR, FECET_PROPUESTA.RFC_SUBADMINISTRADOR, FECET_PROPUESTA.ID_ESTATUS, FECET_PROPUESTA.RFC_FIRMANTE, FECET_PROPUESTA.RFC_AUDITOR, FECET_PROPUESTA.INFORME_PRESENTACION, FECET_PROPUESTA.ID_INSUMO, \n"
            + "FECEC_SUBPROGRAMA.CLAVE, FECEC_SUBPROGRAMA.DESCRIPCION, FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE, FECET_CONTRIBUYENTE.RFC, FECET_CONTRIBUYENTE.NOMBRE, FECET_CONTRIBUYENTE.REGIMEN, FECET_CONTRIBUYENTE.SITUACION, FECET_CONTRIBUYENTE.TIPO, FECET_CONTRIBUYENTE.SITUACION_DOMICILIO, FECET_CONTRIBUYENTE.DOMICILIO_FISCAL, FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE, \n"
            + "FECET_CONTRIBUYENTE.ENTIDAD, FECEC_SECTOR.ID_SECTOR, FECEC_SECTOR.DESCRIPCION DESCRIPCION_SECTOR FROM ";

    String SQL_ORIGEN_CENTRAL_REGIONALES_HEDER = "SELECT  FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_REGISTRO FOLIO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, "
            + "FECET_PROPUESTA.FECHA_FIN_PERIODO, FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.ID_SECTOR, FECET_CONTRIBUYENTE.RFC, FECET_PROPUESTA.PRIORIDAD, "
            + "FECEC_METODO.ABREVIATURA, FECEC_SUBPROGRAMA.CLAVE,FECEC_SUBPROGRAMA.DESCRIPCION, "
            + "FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA, "
            + "FECEC_TIPO_PROPUESTA.DESCRIPCION as DESCRIPCION_TIPO, FECEC_SECTOR.DESCRIPCION DESCRIPCION_SECTOR, FECET_PROPUESTA.FECHA_CREACION,FECET_PROPUESTA.ID_ARACE,"
            + "(select SUM(CASE WHEN FECET_IMPUESTO.FECHA_BAJA IS NULL THEN MONTO ELSE 0 END) from  FECET_IMPUESTO "
            + "WHERE id_propuesta= FECET_PROPUESTA.ID_PROPUESTA  ) AS PRESUNTIVA  \n" + "FROM FECET_PROPUESTA\n"
            + "INNER JOIN FECET_CONTRIBUYENTE ON ( FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE ) \n"
            + "INNER JOIN FECEC_METODO        ON ( FECET_PROPUESTA.ID_METODO        = FECEC_METODO.ID_METODO )  \n"
            + "INNER JOIN FECEC_SUBPROGRAMA   ON ( FECET_PROPUESTA.ID_SUBPROGRAMA =  FECEC_SUBPROGRAMA.ID_SUBPROGRAMA ) \n"
            + "INNER JOIN FECEC_SECTOR ON (FECET_PROPUESTA.ID_SECTOR = FECEC_SECTOR.ID_SECTOR ) \n"
            + "LEFT  JOIN FECET_TRANSFERENCIA ON ( FECET_PROPUESTA.ID_PROPUESTA = FECET_TRANSFERENCIA.ID_PROPUESTA  ) \n"
            + "LEFT  JOIN FECET_IMPUESTO      ON (  FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA)\n"
            + " LEFT JOIN  FECEC_TIPO_PROPUESTA ON   (  FECET_PROPUESTA.ID_TIPO_PROPUESTA = FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA) \n"
            + " LEFT JOIN FECET_INSUMO ON (FECET_INSUMO.ID_REGISTRO = FECET_PROPUESTA.ID_REGISTRO_INSUMO)\n";

    String SQL_ORIGEN_CENTRAL_REGIONALES_WHERE = " WHERE (FECET_PROPUESTA.ID_PROGRAMADOR =? \n"
            + "        and FECET_PROPUESTA.ID_ESTATUS = ?) \n"
            + "        and (FECET_PROPUESTA.ID_INSUMO is null  OR ( FECET_PROPUESTA.ID_INSUMO is not null AND FECET_INSUMO.ID_UNIDAD_ADMINISTRATIVA = 1)   and FECET_PROPUESTA.ID_ARACE = ?) \n"
            + "        GROUP BY FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO , FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.ID_SECTOR, FECET_CONTRIBUYENTE.RFC,  FECET_PROPUESTA.PRIORIDAD, FECEC_METODO.ABREVIATURA, FECEC_SUBPROGRAMA.CLAVE,FECEC_SUBPROGRAMA.DESCRIPCION, FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA,FECEC_TIPO_PROPUESTA.DESCRIPCION,FECEC_SECTOR.DESCRIPCION, FECET_PROPUESTA.FECHA_CREACION,FECET_PROPUESTA.ID_ARACE  \n"
            + "ORDER BY  FECET_PROPUESTA.PRIORIDAD , FECET_PROPUESTA.FECHA_CREACION ";

    String SQL_PROPUESTA_ANALIZAR_HEDER = "SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, FECET_PROPUESTA.ID_SUBPROGRAMA, FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION, FECET_PROPUESTA.ID_TIPO_PROPUESTA, FECET_PROPUESTA.ID_CAUSA_PROGRAMACION, \n"
            + "FECET_PROPUESTA.ID_SECTOR, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO, FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.PRIORIDAD, FECET_PROPUESTA.FECHA_CREACION, FECET_PROPUESTA.FECHA_BAJA, \n"
            + "FECET_PROPUESTA.RFC_CREACION, FECET_PROPUESTA.RFC_ADMINISTRADOR, FECET_PROPUESTA.RFC_SUBADMINISTRADOR, FECET_PROPUESTA.ID_ESTATUS, FECET_PROPUESTA.RFC_FIRMANTE, FECET_PROPUESTA.RFC_AUDITOR, FECET_PROPUESTA.INFORME_PRESENTACION, FECET_PROPUESTA.ID_INSUMO, FECET_PROPUESTA.ID_REGISTRO_INSUMO, \n"
            + "FECEC_SUBPROGRAMA.CLAVE, FECEC_SUBPROGRAMA.DESCRIPCION, FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE, FECET_CONTRIBUYENTE.RFC, FECET_CONTRIBUYENTE.NOMBRE, FECET_CONTRIBUYENTE.REGIMEN, FECET_CONTRIBUYENTE.SITUACION, FECET_CONTRIBUYENTE.TIPO, FECET_CONTRIBUYENTE.SITUACION_DOMICILIO, FECET_CONTRIBUYENTE.DOMICILIO_FISCAL, FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE, \n"
            + "FECEC_METODO.ABREVIATURA, FECET_CONTRIBUYENTE.ENTIDAD, FECEC_SECTOR.ID_SECTOR, FECEC_SECTOR.DESCRIPCION DESCRIPCION_SECTOR, FECEC_ESTATUS.MODULO, FECEC_ESTATUS.DESCRIPCION DESCRIPCION_ESTATUS, FECEC_TIPO_PROPUESTA.DESCRIPCION DESCRIPCION_TIPO_PROPUESTA, \n"
            + " (SELECT SUM(CASE WHEN FECET_IMPUESTO.FECHA_BAJA IS NULL AND FECET_IMPUESTO.ID_RETROALIMENTACION IS NULL THEN MONTO ELSE 0 END) FROM  FECET_IMPUESTO WHERE id_propuesta = FECET_PROPUESTA.ID_PROPUESTA) AS PRESUNTIVA FROM FECET_PROPUESTA ";

    String SQL_PROPUESTA_ANALIZAR_INNER = "INNER JOIN FECEC_SUBPROGRAMA ON FECEC_SUBPROGRAMA.ID_SUBPROGRAMA = FECET_PROPUESTA.ID_SUBPROGRAMA\n"
            + "INNER JOIN FECET_CONTRIBUYENTE ON FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE = FECET_PROPUESTA.ID_CONTRIBUYENTE\n"
            + "INNER JOIN FECEC_SECTOR ON FECEC_SECTOR.ID_SECTOR = FECET_PROPUESTA.ID_SECTOR\n"
            + "LEFT JOIN FECET_IMPUESTO ON FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA\n"
            + "INNER JOIN FECEC_METODO ON FECEC_METODO.ID_METODO = FECET_PROPUESTA.ID_METODO\n"
            + "INNER JOIN FECEC_ESTATUS ON FECEC_ESTATUS.ID_ESTATUS = FECET_PROPUESTA.ID_ESTATUS\n"
            + "INNER JOIN FECEC_TIPO_PROPUESTA ON FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA = FECET_PROPUESTA.ID_TIPO_PROPUESTA";

    String SQL_PROPUESTA_FIRMANTE_HEDER = "SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_REGISTRO FOLIO, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.FECHA_PRESENTACION, FECET_CONTRIBUYENTE.RFC, \n"
            + "FECET_PROPUESTA.FECHA_INICIO_PERIODO,FECET_PROPUESTA.FECHA_FIN_PERIODO, FECET_PROPUESTA.PRIORIDAD, FECET_PROPUESTA.FECHA_CREACION, FECET_PROPUESTA.RFC_CREACION, FECEC_METODO.ABREVIATURA, \n"
            + "FECEC_SUBPROGRAMA.CLAVE, FECEC_SUBPROGRAMA.DESCRIPCION,FECET_IMPUESTO.ID_TIPO_IMPUESTO, FECET_IMPUESTO.MONTO, FECEC_SECTOR.DESCRIPCION SECTOR_DESC, FECEC_TIPO_PROPUESTA.DESCRIPCION PROPUESTA_TIPO_DESC, \n"
            + "FECEC_CONCEPTOS.ID_CONCEPTO \n"
            + FROM_TABLE;

    String SQL_PROPUESTA_FIRMANTE_JOIN = "INNER JOIN FECET_CONTRIBUYENTE ON (  FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE) \n"
            + "INNER JOIN  FECEC_METODO ON (FECET_PROPUESTA.ID_METODO = FECEC_METODO.ID_METODO) \n"
            + "INNER JOIN  FECEC_SUBPROGRAMA ON (FECET_PROPUESTA.ID_SUBPROGRAMA =  FECEC_SUBPROGRAMA.ID_SUBPROGRAMA) \n"
            + "INNER JOIN FECEC_SECTOR ON (FECET_PROPUESTA.ID_SECTOR = FECEC_SECTOR.ID_SECTOR) \n"
            + "INNER JOIN FECEC_TIPO_PROPUESTA ON (FECET_PROPUESTA.ID_TIPO_PROPUESTA = FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA) \n"
            + "LEFT JOIN FECET_IMPUESTO ON (  FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA) \n"
            + "INNER JOIN FECEC_CONCEPTOS ON ( FECET_IMPUESTO.ID_CONCEPTO = FECEC_CONCEPTOS.ID_CONCEPTO) \n"
            + "LEFT JOIN FECET_INSUMO ON (FECET_INSUMO.ID_REGISTRO = FECET_PROPUESTA.ID_REGISTRO_INSUMO)";

    String SQL_INNER_ACCION_PROPUESTA = "INNER JOIN  FECEB_ACCION_PROPUESTA BITACORA_ACCION          ON ( FECET_PROPUESTA.ID_PROPUESTA = BITACORA_ACCION.ID_PROPUESTA )\n"
            + "INNER JOIN  FECEA_PROPUESTA_ACCION PROPUESTA_ACCION         ON ( FECET_PROPUESTA.ID_PROPUESTA = PROPUESTA_ACCION.ID_PROPUESTA )\n"
            + "INNER JOIN  FECEC_ACCIONES_FUNCIONARIO ACCIONES_FUNCIONARIO ON ( PROPUESTA_ACCION.ID_ACCION = ACCIONES_FUNCIONARIO.ID_ACCION ) \n";

    String SQL_CONDICION_WHERE = "WHERE 1=1\n";

    String SQL_PROPUESTA_FIRMANTE_HEDER_UA = "SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_REGISTRO FOLIO, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.FECHA_PRESENTACION, FECET_CONTRIBUYENTE.RFC, \n"
            + "FECET_PROPUESTA.FECHA_INICIO_PERIODO,FECET_PROPUESTA.FECHA_FIN_PERIODO, FECET_PROPUESTA.PRIORIDAD, FECET_PROPUESTA.FECHA_CREACION,  FECEC_METODO.ABREVIATURA, \n"
            + "FECEC_SUBPROGRAMA.CLAVE, FECEC_SUBPROGRAMA.DESCRIPCION, \n"
            + "FECET_IMPUESTO.ID_TIPO_IMPUESTO, FECET_IMPUESTO.MONTO, FECEC_SECTOR.DESCRIPCION SECTOR_DESC, FECEC_TIPO_PROPUESTA.DESCRIPCION PROPUESTA_TIPO_DESC, FECET_PROPUESTA.RFC_CREACION,  FECET_PROPUESTA.RFC_FIRMANTE, \n"
            + "FECEC_CONCEPTOS.ID_CONCEPTO \n"
            + FROM_TABLE;

    String SQL_PROPUESTA_FIRMANTE_JOIN_UA = "INNER JOIN FECET_CONTRIBUYENTE ON (  FECET_PROPUESTA.ID_CONTRIBUYENTE = FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE) \n"
            + "INNER JOIN  FECEC_METODO ON (FECET_PROPUESTA.ID_METODO = FECEC_METODO.ID_METODO) \n"
            + "INNER JOIN  FECEC_SUBPROGRAMA ON (FECET_PROPUESTA.ID_SUBPROGRAMA =  FECEC_SUBPROGRAMA.ID_SUBPROGRAMA) \n"
            + "INNER JOIN FECEC_SECTOR ON (FECET_PROPUESTA.ID_SECTOR = FECEC_SECTOR.ID_SECTOR) \n"
            + "INNER JOIN FECEC_TIPO_PROPUESTA ON (FECET_PROPUESTA.ID_TIPO_PROPUESTA = FECEC_TIPO_PROPUESTA.ID_TIPO_PROPUESTA) \n"
            + "LEFT JOIN FECET_IMPUESTO ON (  FECET_PROPUESTA.ID_PROPUESTA = FECET_IMPUESTO.ID_PROPUESTA) \n"
            + "INNER JOIN FECEC_CONCEPTOS ON ( FECET_IMPUESTO.ID_CONCEPTO = FECEC_CONCEPTOS.ID_CONCEPTO)";

    String SQL_SELECT_PROPUESTAS_RECHAZADAS_X_VALID = "SELECT FECET_PROPUESTA.ID_PROPUESTA, FECET_PROPUESTA.ID_CONTRIBUYENTE, FECET_PROPUESTA.ID_ARACE, FECET_PROPUESTA.ID_SUBPROGRAMA, \n"
            + "FECET_PROPUESTA.ID_METODO, FECET_PROPUESTA.ID_REVISION, FECET_PROPUESTA.ID_TIPO_PROPUESTA,  FECET_PROPUESTA.ID_CAUSA_PROGRAMACION, \n"
            + "FECET_PROPUESTA.ID_SECTOR, FECET_PROPUESTA.ID_REGISTRO, FECET_PROPUESTA.FECHA_INICIO_PERIODO, FECET_PROPUESTA.FECHA_FIN_PERIODO, \n"
            + "FECET_PROPUESTA.FECHA_PRESENTACION, FECET_PROPUESTA.FECHA_INFORME, FECET_PROPUESTA.PRIORIDAD, \n"
            + "FECET_PROPUESTA.FECHA_CREACION, FECET_PROPUESTA.FECHA_BAJA, FECET_PROPUESTA.RFC_CREACION, FECET_PROPUESTA.RFC_ADMINISTRADOR, \n"
            + "FECET_PROPUESTA.RFC_SUBADMINISTRADOR, FECET_PROPUESTA.ID_ESTATUS, FECET_PROPUESTA.RFC_AUDITOR, FECET_PROPUESTA.RFC_FIRMANTE, \n"
            + "FECET_PROPUESTA.INFORME_PRESENTACION, FECET_PROPUESTA.ID_INSUMO, FECET_PROPUESTA.ID_REGISTRO_INSUMO, \n"
            + "FECET_PROPUESTA.ID_ORIGEN, \n"
            + "FECEC_SUBPROGRAMA.ID_SUBPROGRAMA AS SUB_ID_SUBPROGRAMA,  FECEC_SUBPROGRAMA.CLAVE,  FECEC_SUBPROGRAMA.DESCRIPCION, \n"
            + "FECEC_SUBPROGRAMA.DESCRIPCION AS DESCRIPCION_SUBPROGRAMA,  FECET_CONTRIBUYENTE.ID_CONTRIBUYENTE AS CONT_ID_CONTRIBUYENTE, \n"
            + "FECET_CONTRIBUYENTE.RFC,   FECET_CONTRIBUYENTE.NOMBRE,  FECET_CONTRIBUYENTE.REGIMEN, FECET_CONTRIBUYENTE.SITUACION, \n"
            + "FECET_CONTRIBUYENTE.TIPO, FECET_CONTRIBUYENTE.SITUACION_DOMICILIO, FECET_CONTRIBUYENTE.DOMICILIO_FISCAL,  \n"
            + "FECET_CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE,  FECET_CONTRIBUYENTE.ENTIDAD, FECEC_ESTATUS.ID_ESTATUS AS ESTATUS_ID_ESTATUS, \n"
            + "FECEC_ESTATUS.DESCRIPCION AS DESCRIPCION_ESTATUS,  FECEC_ESTATUS.MODULO,  FECEC_SECTOR.ID_SECTOR AS SECTOR_ID_SECTOR, \n"
            + "FECEC_SECTOR.DESCRIPCION AS DESCRIPCION_SECTOR, \n"
            + "FECEC_METODO.ID_METODO, FECEC_METODO.ABREVIATURA,FECEC_METODO.NOMBRE AS NOMBRE_METODO, \n"
            + "NVL(SUM(FECET_IMPUESTO.MONTO),0) AS PRESUNTIVA \n" + FROM_TABLE;

    String SQL_RESUMEN_PROPUESTAS_FIRMANTE = new StringBuilder().append("SELECT ").append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 143 AND PA.ID_ACCION_ORIGEN IS NULL) CANCELADAS_VALIDAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 143 AND PA.ID_ACCION_ORIGEN = 22) CANCELADADAS_NO_APROBAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 143 AND PA.ID_ACCION_ORIGEN = 14) CANCELADAS_EMISION, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 62 AND PA.ID_ACCION_ORIGEN IS NULL) RECHAZADAS_VALIDAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 62 AND PA.ID_ACCION_ORIGEN = 22) RECHAZADAS_NO_APROBAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 62 AND PA.ID_ACCION_ORIGEN = 14) RECHAZADAS_EMISION, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 120 AND PA.ID_ACCION_ORIGEN IS NULL) TRANSFERIDAS_VALIDAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 120 AND PA.ID_ACCION_ORIGEN = 22) TRANSFERIDAS_NO_APROBAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 120 AND PA.ID_ACCION_ORIGEN = 14) TRANSFERIDAS_EMISION, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 145 AND PA.ID_ACCION_ORIGEN IS NULL) RETROALIMENTADAS_VALIDAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 145 AND PA.ID_ACCION_ORIGEN = 22) RETROALIMENTADAS_NO_APROBAR, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 145 AND PA.ID_ACCION_ORIGEN = 14) RETROALIMENTADAS_EMISION, ")
            .append(" (SELECT COUNT(0) FROM FECET_PROPUESTA P WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND (P.ID_ESTATUS = 72 OR P.ID_ESTATUS = 52)) RETROALIMENTADAS_INFORMADAS, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 57 AND PA.ID_ACCION_ORIGEN = 22) REVISION_NO_APROBADA, ")
            .append(COUNT_ACCIONES_PROPUESTAS)
            .append("WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 57 AND PA.ID_ACCION_ORIGEN = 14) REVISION_EMISION, ")
            .append("   (SELECT COUNT(0) FROM FECET_PROPUESTA P WHERE P.FECHA_BAJA IS NULL AND P.RFC_FIRMANTE = ? AND P.ID_ESTATUS = 61) REVISION_INFORMADA ")
            .append("FROM DUAL ").toString();

    String SQL_RESUMEN_PROPUESTA_FIRMANTE_DETALLE_HEADER = new StringBuilder(
            "SELECT PROPUESTA.ID_PROPUESTA, PROPUESTA.ID_CONTRIBUYENTE, PROPUESTA.ID_ARACE, PROPUESTA.ID_SUBPROGRAMA, ")
            .append("\n PROPUESTA.ID_METODO, PROPUESTA.ID_REVISION, PROPUESTA.ID_TIPO_PROPUESTA, PROPUESTA.ID_CAUSA_PROGRAMACION, PROPUESTA.ID_SECTOR, PROPUESTA.ID_REGISTRO, ")
            .append("\n PROPUESTA.FECHA_INICIO_PERIODO, PROPUESTA.FECHA_FIN_PERIODO, PROPUESTA.FECHA_PRESENTACION, PROPUESTA.FECHA_INFORME, PROPUESTA.PRIORIDAD, ")
            .append("\n PROPUESTA.FECHA_CREACION, PROPUESTA.FECHA_BAJA, PROPUESTA.RFC_CREACION, PROPUESTA.RFC_ADMINISTRADOR, PROPUESTA.RFC_SUBADMINISTRADOR, PROPUESTA.ID_ESTATUS, ")
            .append("\n PROPUESTA.RFC_AUDITOR, PROPUESTA.RFC_FIRMANTE, PROPUESTA.INFORME_PRESENTACION, PROPUESTA.ID_INSUMO, PROPUESTA.ID_REGISTRO_INSUMO, PROPUESTA.ID_ORIGEN, PROPUESTA.CONSECUTIVO_ANO, ")
            .append("\n PROPUESTA.ID_PROGRAMADOR, CONTRIBUYENTE.RFC, CONTRIBUYENTE.NOMBRE, CONTRIBUYENTE.REGIMEN, CONTRIBUYENTE.SITUACION, CONTRIBUYENTE.TIPO, ")
            .append("\n CONTRIBUYENTE.SITUACION_DOMICILIO, CONTRIBUYENTE.DOMICILIO_FISCAL, CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE, CONTRIBUYENTE.ENTIDAD, ")
            .append("\n METODO.ABREVIATURA, METODO.NOMBRE DESCRIPCION_METODO, SECTOR.DESCRIPCION DESCRIPCION_SECTOR, ")
            .append("\n SUBPROGRAMA.CLAVE, SUBPROGRAMA.DESCRIPCION DESCRIPCION_SUBPROGRAMA, CAUSA_PRO.DESCRIPCION DESCRIPCION_CAUSA_PROGRAMACION, TIPO_PROPUESTA.DESCRIPCION DESCRIPCION_TIPO_PROPUESTA, ")
            .append("\n (SELECT SUM(CASE WHEN FECET_IMPUESTO.FECHA_BAJA IS NULL AND FECET_IMPUESTO.ID_RETROALIMENTACION IS NULL THEN MONTO ELSE 0 END) FROM FECET_IMPUESTO WHERE ID_PROPUESTA = PROPUESTA.ID_PROPUESTA) AS PRESUNTIVA, ")
            .append("\n REVISION.DESCRIPCION DESC_REVISION").append("\n FROM FECET_PROPUESTA PROPUESTA ")
            .append("\n JOIN FECEC_METODO METODO ON METODO.ID_METODO = PROPUESTA.ID_METODO ")
            .append("\n JOIN FECEC_CAUSA_PROGRAMACION CAUSA_PRO ON CAUSA_PRO.ID_CAUSA_PROGRAMACION = PROPUESTA.ID_CAUSA_PROGRAMACION ")
            .append("\n JOIN FECEC_TIPO_PROPUESTA TIPO_PROPUESTA ON TIPO_PROPUESTA.ID_TIPO_PROPUESTA = PROPUESTA.ID_TIPO_PROPUESTA ")
            .append("\n JOIN FECEC_SECTOR SECTOR ON SECTOR.ID_SECTOR = PROPUESTA.ID_SECTOR ")
            .append("\n JOIN FECEC_SUBPROGRAMA SUBPROGRAMA ON SUBPROGRAMA.ID_SUBPROGRAMA = PROPUESTA.ID_SUBPROGRAMA ")
            .append("\n JOIN FECET_CONTRIBUYENTE CONTRIBUYENTE ON CONTRIBUYENTE.ID_CONTRIBUYENTE = PROPUESTA.ID_CONTRIBUYENTE")
            .append("\n LEFT JOIN FECEC_REVISION REVISION ON REVISION.ID_REVISION = PROPUESTA.ID_REVISION ")
            .toString();

    String SQL_RESUMEN_PROPUESTA_FIRMANTE_ACCION = "\n INNER JOIN FECEA_PROPUESTA_ACCION ACCION ON ACCION.ID_PROPUESTA = PROPUESTA.ID_PROPUESTA AND ACCION.ID_ACCION_ORIGEN = ? ";

    String SQL_RESUMEN_PROPUESTA_FIRMANTE_ACCION_NULL = "\n INNER JOIN FECEA_PROPUESTA_ACCION ACCION ON ACCION.ID_PROPUESTA = PROPUESTA.ID_PROPUESTA AND ACCION.ID_ACCION_ORIGEN IS NULL ";

    String SQL_CONDICION_POR_VALIDAR = "AND PROPUESTA.ID_ESTATUS = ? AND PROPUESTA.RFC_FIRMANTE = ? AND PROPUESTA.FECHA_BAJA IS NULL ";

    String SQL_CONDICION_POR_VALIDAR_ORDER = "ORDER BY PROPUESTA.PRIORIDAD, PROPUESTA.FECHA_CREACION ";
}
