package mx.gob.sat.siat.feagace.modelo.dao.propuestas.sql;

public interface PropuestaAccionSQL {

    String CAMPOS_BITACORA_ACCION_PROPUESTA = "BITACORA.ID_ACCION_PROPUESTA, BITACORA.ID_PROPUESTA, "
            + "BITACORA.ID_DETALLE_ACCION, BITACORA.ID_ACCION, BITACORA.ID_ACCION_ORIGEN, BITACORA.OBSERVACIONES,"
            + " BITACORA.FECHA_HORA, BITACORA.ID_EMPLEADO";

    String CAMPOS_ACCIONES_FUNCIONARIO = "ACCIONES.ID_ACCION ACCION_ID_ACCION, ACCIONES.DESCRIPCION, ACCIONES.ID_TIPO_EMPLEADO, "
            + "ACCIONES.FECHA_INICIO, ACCIONES.FECHA_FIN, ACCIONES.BLN_ESTATUS ";

    String INNER_JOIN_FUNCIONARIO_ACCION = "INNER JOIN FECEC_ACCIONES_FUNCIONARIO ACCIONES ON BITACORA.ID_ACCION = ACCIONES.ID_ACCION";

    String INNER_JOIN_RECHAZO_ACCION = "INNER JOIN FECET_RECHAZO_PROPUESTA RECHAZO ON RECHAZO.ID_RECHAZO_PROPUESTA = BITACORA.ID_DETALLE_ACCION";

    String INNER_JOIN_CANCELACION_ACCION = "INNER JOIN FECET_CANCELACION CANCELACION ON CANCELACION.ID_CANCELACION = BITACORA.ID_DETALLE_ACCION";

    String INNER_JOIN_RETROALIMENTACION_ACCION = "INNER JOIN FECET_RETROALIMENTACION RETROALIMENTAR ON RETROALIMENTAR.ID_RETROALIMENTACION = BITACORA.ID_DETALLE_ACCION";

    String INNER_JOIN_TRANSFERIR_ACCION = "INNER JOIN FECET_TRANSFERENCIA TRANSFERENCIA ON TRANSFERENCIA.ID_TRANSFERENCIA = BITACORA.ID_DETALLE_ACCION";

    String INNER_JOIN_DOC_RECHAZO = "INNER JOIN FECET_DOC_RECHAZO_PROPUESTA DOC ON DOC.ID_RECHAZO_PROPUESTA = RECHAZO.ID_RECHAZO_PROPUESTA";

    String INNER_JOIN_DOC_CANCELACION = "INNER JOIN FECET_DOC_CANCELACION DOC ON DOC.ID_CANCELACION = CANCELACION.ID_CANCELACION";

    String INNER_JOIN_DOC_RETROALIMENTACION = "INNER JOIN FECET_DOC_RETRO_PROPUESTA DOC ON DOC.ID_RETROALIMENTACION = RETROALIMENTAR.ID_RETROALIMENTACION";

    String INNER_JOIN_DOC_TRANSFERIR = "INNER JOIN FECET_DOC_TRANSFERENCIA DOC ON DOC.ID_TRANSFERENCIA = TRANSFERENCIA.ID_TRANSFERENCIA";

    String INNER_JOIN_MOTIVO_RECHAZO = "INNER JOIN FECEC_MOTIVO MOTIVO ON MOTIVO.ID_MOTIVO = RECHAZO.ID_MOTIVO";

    String INNER_JOIN_MOTIVO_CANCELACION = "INNER JOIN FECEC_MOTIVO MOTIVO ON MOTIVO.ID_MOTIVO = CANCELACION.ID_CAUSA";

    String INNER_JOIN_MOTIVO_RETROALIMENTACION = "LEFT JOIN FECEC_MOTIVO MOTIVO ON MOTIVO.ID_MOTIVO = RETROALIMENTAR.ID_MOTIVO";

    String GROUP_BY_RECHAZO = "GROUP BY BITACORA.ID_ACCION_PROPUESTA, BITACORA.ID_PROPUESTA, BITACORA.ID_DETALLE_ACCION, BITACORA.ID_ACCION, \n"
            + "BITACORA.ID_ACCION_ORIGEN, BITACORA.OBSERVACIONES, BITACORA.FECHA_HORA, BITACORA.ID_EMPLEADO,  RECHAZO.ID_RECHAZO_PROPUESTA, RECHAZO.DESCRIPCION, \n"
            + "ACCIONES.ID_ACCION , ACCIONES.DESCRIPCION, ACCIONES.ID_TIPO_EMPLEADO, ACCIONES.FECHA_INICIO, ACCIONES.FECHA_FIN, ACCIONES.BLN_ESTATUS,MOTIVO.DESCRIPCION \n";

    String GROUP_BY_CANCELACION = "GROUP BY BITACORA.ID_ACCION_PROPUESTA, BITACORA.ID_PROPUESTA, BITACORA.ID_DETALLE_ACCION, BITACORA.ID_ACCION, BITACORA.ID_ACCION_ORIGEN, \n"
            + "CANCELACION.ID_CANCELACION, CANCELACION.OBSERVACIONES, BITACORA.OBSERVACIONES, BITACORA.FECHA_HORA, BITACORA.ID_EMPLEADO, \n"
            + "ACCIONES.ID_ACCION , ACCIONES.DESCRIPCION, ACCIONES.ID_TIPO_EMPLEADO, ACCIONES.FECHA_INICIO, ACCIONES.FECHA_FIN, ACCIONES.BLN_ESTATUS, MOTIVO.DESCRIPCION \n";

    String GROUP_BY_RETROALIMENTACION = "GROUP BY BITACORA.ID_ACCION_PROPUESTA, BITACORA.ID_PROPUESTA, BITACORA.ID_DETALLE_ACCION, BITACORA.ID_ACCION, BITACORA.ID_ACCION_ORIGEN, BITACORA.OBSERVACIONES, BITACORA.FECHA_HORA, BITACORA.ID_EMPLEADO, \n"
            + "ACCIONES.ID_ACCION , ACCIONES.DESCRIPCION, ACCIONES.ID_TIPO_EMPLEADO, ACCIONES.FECHA_INICIO, ACCIONES.FECHA_FIN, \n"
            + "RETROALIMENTAR.ID_RETROALIMENTACION,RETROALIMENTAR.DESCRIPCION,ACCIONES.BLN_ESTATUS, MOTIVO.DESCRIPCION \n";

    String GROUP_BY_TRANSFERIR = "GROUP BY BITACORA.ID_ACCION_PROPUESTA, BITACORA.ID_PROPUESTA, BITACORA.ID_DETALLE_ACCION, BITACORA.ID_ACCION, BITACORA.ID_ACCION_ORIGEN, BITACORA.OBSERVACIONES, BITACORA.FECHA_HORA, BITACORA.ID_EMPLEADO, \n"
            + "ACCIONES.ID_ACCION , ACCIONES.DESCRIPCION, ACCIONES.ID_TIPO_EMPLEADO, ACCIONES.FECHA_INICIO, ACCIONES.FECHA_FIN, ACCIONES.BLN_ESTATUS, \n"
            + "TRANSFERENCIA.ID_TRANSFERENCIA, TRANSFERENCIA.OBSERVACIONES \n";
}
