package mx.gob.sat.siat.feagace.modelo.dao.insumos.consultageneral;

import java.math.BigDecimal;
import java.util.List;

import mx.gob.sat.siat.feagace.modelo.dto.catalogos.roles.EmpleadoDTO;
import mx.gob.sat.siat.feagace.modelo.dto.insumos.FecetInsumo;

public interface ConsultaGeneralInsumosDAO {

    String DETALLE_INSUMO = "select INSUMO.ID_INSUMO ID_INSUMO, INSUMO.ID_CONTRIBUYENTE ID_CONTRIBUYENTE, "
            + "INSUMO.ID_UNIDAD_ADMINISTRATIVA ID_UNIDAD_ADMINISTRATIVA, INSUMO.ID_SUBPROGRAMA ID_SUBPROGRAMA, INSUMO.ID_SECTOR ID_SECTOR, "
            + "INSUMO.ID_REGISTRO ID_REGISTRO, INSUMO.FECHA_INICIO_PERIODO FECHA_INICIO_PERIODO, "
            + "INSUMO.FECHA_FIN_PERIODO FECHA_FIN_PERIODO, INSUMO.PRIORIDAD PRIORIDAD, "
            + "INSUMO.FECHA_CREACION FECHA_CREACION, INSUMO.FECHA_BAJA FECHA_BAJA, INSUMO.RFC_CREACION RFC_CREACION, "
            + "INSUMO.RFC_ADMINISTRADOR RFC_ADMINISTRADOR, INSUMO.RFC_SUBADMINISTRADOR RFC_SUBADMINISTRADOR, "
            + "INSUMO.ID_ESTATUS ID_ESTATUS, INSUMO.ID_PRIORIDAD ID_PRIORIDAD, INSUMO.FECHA_INICIO_PLAZO FECHA_INICIO_PLAZO, "
            + "CONTRIBUYENTE.RFC CONTRIBUYENTE_RFC, CONTRIBUYENTE.NOMBRE CONTRIBUYENTE_NOMBRE, "
            + "CONTRIBUYENTE.REGIMEN CONTRIBUYENTE_REGIMEN, CONTRIBUYENTE.SITUACION CONTRIBUYENTE_SITUACION, "
            + "CONTRIBUYENTE.TIPO CONTRIBUYENTE_TIPO, CONTRIBUYENTE.SITUACION_DOMICILIO SITUACION_DOMICILIO, "
            + "CONTRIBUYENTE.DOMICILIO_FISCAL DOMICILIO_FISCAL, CONTRIBUYENTE.ACTIVIDAD_PREPONDERANTE ACTIVIDAD_PREPONDERANTE, "
            + "CONTRIBUYENTE.ENTIDAD CONTRIBUYENTE_ENTIDAD, PRIORIDAD.VALOR PRIORIDAD_VALOR, PRIORIDAD.FECHA_INICIO PRIORIDAD_FECHA_INICIO, "
            + "PRIORIDAD.FECHA_FIN PRIORIDAD_FECHA_FIN, PRIORIDAD.BLN_ACTIVO PRIORIDAD_BLN_ACTIVO, "
            + "ESTATUS.DESCRIPCION ESTATUS_DESCRIPCION, ESTATUS.MODULO ESTATUS_MODULO, ESTATUS.ID_MODULO ESTATUS_ID_MODULO, "
            + "SECTOR.DESCRIPCION SECTOR_DESCRIPCION, SUBPROGRAMA.CLAVE SUBPROGRAMA_CLAVE, SUBPROGRAMA.DESCRIPCION SUBPROGRAMA_DESCRIPCION, "
            + "DOC_EXP_INSUMO.ID_DOC_EXP_INSUMO DOC_INSUMO_ID, DOC_EXP_INSUMO.RUTA_ARCHIVO DOC_INSUMO_RUTA_ARCHIVO, "
            + "DOC_EXP_INSUMO.FECHA_CREACION DOC_INSUMO_FECHA_CREACION, DOC_EXP_INSUMO.FECHA_FIN DOC_INSUMO_FECHA_FIN, "
            + "DOC_EXP_INSUMO.BLN_ACTIVO DOC_INSUMO_BLN_ACTIVO FROM FECET_INSUMO INSUMO INNER JOIN FECET_CONTRIBUYENTE "
            + "CONTRIBUYENTE ON INSUMO.ID_CONTRIBUYENTE = CONTRIBUYENTE.ID_CONTRIBUYENTE INNER JOIN FECEC_PRIORIDAD "
            + "PRIORIDAD ON PRIORIDAD.ID_PRIORIDAD = INSUMO.ID_PRIORIDAD INNER JOIN FECEC_ESTATUS  "
            + "ESTATUS ON INSUMO.ID_ESTATUS = ESTATUS.ID_ESTATUS INNER JOIN FECEC_SECTOR SECTOR "
            + "ON SECTOR.ID_SECTOR = INSUMO.ID_SECTOR INNER JOIN FECEC_SUBPROGRAMA SUBPROGRAMA ON SUBPROGRAMA.ID_SUBPROGRAMA = "
            + "INSUMO.ID_SUBPROGRAMA INNER JOIN FECET_DOC_EXP_INSUMO DOC_EXP_INSUMO ON INSUMO.ID_INSUMO = "
            + "DOC_EXP_INSUMO.ID_INSUMO where INSUMO.ID_ESTATUS in (1, 3, 4, 5, 6, 7, 11, 12, 14) ";

    String DETALLE_INSUMO_FILTRO_ADMINISTRADORES = "AND RFC_ADMINISTRADOR IN ";

    String DETALLE_INSUMO_FILTRO_SUB_ADMINISTRADORES = "AND RFC_ADMINISTRADOR = ";

    String DETALLE_INSUMO_FILTRO_SUBADMINISTRADORES = "AND RFC_SUBADMINISTRADOR IN ";

    String DETALLE_INSUMO_FILTRO_CREADOR = "AND RFC_CREACION IN ";

    String DETALLE_INSUMO_FILTRO_UNIDADADMON = "AND ID_UNIDAD_ADMINISTRATIVA = ";

    String DETALLE_INSUMO_FILTRO_ESTATUS = "AND INSUMO.ID_ESTATUS IN ";

    List<FecetInsumo> consultarInsumosEstatusInicial(List<EmpleadoDTO> empleados, BigDecimal idUnidadAdmonRecepcion);

    List<FecetInsumo> consultarInsumosEstatusAdmon(List<EmpleadoDTO> admons, String estatus, String condicion);

    List<FecetInsumo> consultarInsumosEstatusSubAdmon(EmpleadoDTO empleado, List<EmpleadoDTO> subAdmons, String estatus, String condicion);

}
